package com.evidu.bank.entitiy;

public class Account {
	
	private String TNP_CX_PROFILE_UUID;
	private String TNP_CX_PROFILE_KYC_FORM_NO;
	private String TNP_CX_PROFILE_REF_NO;
	private String TNP_CX_PROFILE_TYPE;
	private String TNP_CX_PROFILE_CREATED_BY;
	private String TNP_CX_PROFILE_CREATED_BRANCH;
	private String TNP_CX_PROFILE_CREATED_DATE;
	private String TNP_CX_PROFILE_MODIFIED_BY;
	private String TNP_CX_PROFILE_MODIFIED_DATE;
	private String TNP_CX_PROFILE_MODIFIED_COMMENT;
	private String TNP_CX_PROFILE_STATUS;
	private String TNP_CX_PROFILE_MOBILE_NUMBER;
	private String TNP_CX_PROFILE_NAME;
	private String TNP_CX_PROFILE_DATE_OF_BIRTH; 
	private String TNP_CX_PROFILE_GENDER;
	private String TNP_CX_PROFILE_NATIONALITY;
	private String TNP_CX_PROFILE_ID_NUMBER; 
	private String TNP_CX_PROFILE_ID_TYPE; 
	private String TNP_CX_PROFILE_TIN_NO;
	private String TNP_CX_PROFILE_EMAIL_ID;
	private String TNP_CX_PROFILE_OTHER_CONTACT_NO;
	private String TNP_CX_PROFILE_EMERGENCY_CONTACT_NO;
	private String TNP_CX_PROFILE_PROFESSION;
	private String TNP_CX_PROFILE_FATHER_NAME;
	private String TNP_CX_PROFILE_MOTHER_NAME;
	private String TNP_CX_PROFILE_SPOUSE_NAME;
	private String TNP_CX_PROFILE_PERMANENT_ADDRESS_HOUSE_NO;  
	private String TNP_CX_PROFILE_PERMANENT_ADDRESS_STREET; 
	private String TNP_CX_PROFILE_PERMANENT_ADDRESS_CITY; 
	private String TNP_CX_PROFILE_PERMANENT_ADDRESS_STATE; 
	private String TNP_CX_PROFILE_PERMANENT_ADDRESS_DISTRICT;
	private String TNP_CX_PROFILE_PERMANENT_ADDRESS_THANA;
	private String TNP_CX_PROFILE_PERMANENT_ADDRESS_UNION;
	private String TNP_CX_PROFILE_PERMANENT_ADDRESS_DIVISION;
	private String TNP_CX_PROFILE_PERMANENT_ADDRESS_POSTCODE;
	private String TNP_CX_PROFILE_MAILING_ADDRESS_HOUSE_NO;  
	private String TNP_CX_PROFILE_MAILING_ADDRESS_STREET; 
	private String TNP_CX_PROFILE_MAILING_ADDRESS_CITY; 
	private String TNP_CX_PROFILE_MAILING_ADDRESS_STATE; 
	private String TNP_CX_PROFILE_MAILING_ADDRESS_DISTRICT;
	private String TNP_CX_PROFILE_MAILING_ADDRESS_THANA;
	private String TNP_CX_PROFILE_MAILING_ADDRESS_UNION;
	private String TNP_CX_PROFILE_MAILING_ADDRESS_DIVISION;
	private String TNP_CX_PROFILE_MAILING_ADDRESS_POSTCODE;
	private String TNP_CX_PROFILE_PURPOSE_OF_TRANSACTIONS;
	private String TNP_CX_PROFILE_BANK_ACC_NO;
	private String TNP_CX_PROFILE_BANK_ACC_NAME;
	private String TNP_CX_PROFILE_BANK_NAME;
	private String TNP_CX_PROFILE_BANK_BRANCH;
	private String TNP_CX_PROFILE_NOMINEE_NAME;
	private String TNP_CX_PROFILE_NOMINEE_RELATION;
	private String TNP_CX_PROFILE_NOMINEE_CONTACT_NO; 
	private String TNP_CX_PROFILE_NOMINEE_FATHERS_NAME;
	private String TNP_CX_PROFILE_NOMINEE_MOTHERS_NAME;
	private String TNP_CX_PROFILE_NOMINEE_ID_TYPE;
	private String TNP_CX_PROFILE_NOMINEE_ID_NUMBER;
	private String TNP_CX_PROFILE_NOMINEE_ADDRESS_HOUSE_NO;  
	private String TNP_CX_PROFILE_NOMINEE_ADDRESS_STEET; 
	private String TNP_CX_PROFILE_NOMINEE_ADDRESS_CITY;
	private String TNP_CX_PROFILE_NOMINEE_ADDRESS_STATE; 
	private String TNP_CX_PROFILE_NOMINEE_DISTRICT;
	private String TNP_CX_PROFILE_NOMINEE_THANA;
	private String TNP_CX_PROFILE_NOMINEE_UNION;
	private String TNP_CX_PROFILE_NOMINEE_DIVISION;
	private String TNP_CX_PROFILE_NOMINEE_POSTCODE;
	private String TNP_CX_PROFILE_INTRODUCER_ID;
	private String TNP_CX_PROFILE_INTRODUCER_NAME;
	private String TNP_CX_PROFILE_INTRODUCER_BRANCH_NAME;
	private String TNP_CX_PROFILE_INTRODUCER_MOBILE_NUM;  
	private String TNP_CX_PROFILE_INTRODUCER_HOME_NO;
	private String TNP_CX_PROFILE_INTRODUCER_CITY;
	private String TNP_CX_PROFILE_INTRODUCER_STREET;
	private String TNP_CX_PROFILE_INTRODUCER_STATE;
	private String TNP_CX_PROFILE_INTRODUCER_DISTRICT;
	private String TNP_CX_PROFILE_INTRODUCER_THANA;
	private String TNP_CX_PROFILE_INTRODUCER_UNION;
	private String TNP_CX_PROFILE_VERIFIED_USER;
	private String TNP_CX_PROFILE_APPROVAL_STATUS;
	private String TNP_CX_PROFILE_APPROVAL_COMMENTS;
	private String TNP_CX_PROFILE_REFERANCE_NO_OTHER;
	private String TNP_CX_PROFILE_VERIFIED_IMG_NIC; 
	private String TNP_CX_PROFILE_VERIFIED_IMG_PHOTO; 
	private String TNP_CX_PROFILE_VERIFIED_IMG_KYC_FORM;
	private String TNP_CX_PROFILE_VERIFIED_IMG_TIN_FORM;
	private String TNP_CX_PROFILE_VERIFIED_CITIZENSHIP_CERITIFICATE_FROM;
	private String TNP_CX_PROFILE_VERIFIED_IMG_OTHER;
	private String TNP_CX_PROFILE_INFO1;
	private String TNP_CX_PROFILE_INFO2;
	private String TNP_CX_PROFILE_INFO3;
	private String TNP_CX_PROFILE_INFO4;
	private String TNP_CX_PROFILE_INFO5;
	private String lockStatus;
	private String lockBy;
	private String lockTime;
	private String NID_PATH;
	private String PHOTO_PATH;
	private String KYC_FORM_PATH;
	private String TIN_FORM_PATH;
	private String OTHER_PATH;
	private int statusCode;
	private String statusMsg;
	private String request_id;
	
	public String getRequest_id() {
		return request_id;
	}
	public void setRequest_id(String request_id) {
		this.request_id = request_id;
	}
	public int getStatusCode() {
		return statusCode;
	}
	public void setStatusCode(int statusCode) {
		this.statusCode = statusCode;
	}
	public String getStatusMsg() {
		return statusMsg;
	}
	public void setStatusMsg(String statusMsg) {
		this.statusMsg = statusMsg;
	}
	public String getNID_PATH() {
		return NID_PATH;
	}
	public void setNID_PATH(String nID_PATH) {
		NID_PATH = nID_PATH;
	}
	public String getPHOTO_PATH() {
		return PHOTO_PATH;
	}
	public void setPHOTO_PATH(String pHOTO_PATH) {
		PHOTO_PATH = pHOTO_PATH;
	}
	public String getKYC_FORM_PATH() {
		return KYC_FORM_PATH;
	}
	public void setKYC_FORM_PATH(String kYC_FORM_PATH) {
		KYC_FORM_PATH = kYC_FORM_PATH;
	}
	public String getTIN_FORM_PATH() {
		return TIN_FORM_PATH;
	}
	public void setTIN_FORM_PATH(String tIN_FORM_PATH) {
		TIN_FORM_PATH = tIN_FORM_PATH;
	}
	public String getOTHER_PATH() {
		return OTHER_PATH;
	}
	public void setOTHER_PATH(String oTHER_PATH) {
		OTHER_PATH = oTHER_PATH;
	}
	public String getLockStatus() {
		return lockStatus;
	}
	public void setLockStatus(String lockStatus) {
		this.lockStatus = lockStatus;
	}
	public String getLockBy() {
		return lockBy;
	}
	public void setLockBy(String lockBy) {
		this.lockBy = lockBy;
	}
	public String getLockTime() {
		return lockTime;
	}
	public void setLockTime(String lockTime) {
		this.lockTime = lockTime;
	}
	public String getTNP_CX_PROFILE_UUID() {
		return TNP_CX_PROFILE_UUID;
	}
	public void setTNP_CX_PROFILE_UUID(String tNP_CX_PROFILE_UUID) {
		TNP_CX_PROFILE_UUID = tNP_CX_PROFILE_UUID;
	}
	public String getTNP_CX_PROFILE_KYC_FORM_NO() {
		return TNP_CX_PROFILE_KYC_FORM_NO;
	}
	public void setTNP_CX_PROFILE_KYC_FORM_NO(String tNP_CX_PROFILE_KYC_FORM_NO) {
		TNP_CX_PROFILE_KYC_FORM_NO = tNP_CX_PROFILE_KYC_FORM_NO;
	}
	public String getTNP_CX_PROFILE_REF_NO() {
		return TNP_CX_PROFILE_REF_NO;
	}
	public void setTNP_CX_PROFILE_REF_NO(String tNP_CX_PROFILE_REF_NO) {
		TNP_CX_PROFILE_REF_NO = tNP_CX_PROFILE_REF_NO;
	}
	public String getTNP_CX_PROFILE_TYPE() {
		return TNP_CX_PROFILE_TYPE;
	}
	public void setTNP_CX_PROFILE_TYPE(String tNP_CX_PROFILE_TYPE) {
		TNP_CX_PROFILE_TYPE = tNP_CX_PROFILE_TYPE;
	}
	public String getTNP_CX_PROFILE_CREATED_BY() {
		return TNP_CX_PROFILE_CREATED_BY;
	}
	public void setTNP_CX_PROFILE_CREATED_BY(String tNP_CX_PROFILE_CREATED_BY) {
		TNP_CX_PROFILE_CREATED_BY = tNP_CX_PROFILE_CREATED_BY;
	}
	public String getTNP_CX_PROFILE_CREATED_BRANCH() {
		return TNP_CX_PROFILE_CREATED_BRANCH;
	}
	public void setTNP_CX_PROFILE_CREATED_BRANCH(String tNP_CX_PROFILE_CREATED_BRANCH) {
		TNP_CX_PROFILE_CREATED_BRANCH = tNP_CX_PROFILE_CREATED_BRANCH;
	}
	public String getTNP_CX_PROFILE_CREATED_DATE() {
		return TNP_CX_PROFILE_CREATED_DATE;
	}
	public void setTNP_CX_PROFILE_CREATED_DATE(String tNP_CX_PROFILE_CREATED_DATE) {
		TNP_CX_PROFILE_CREATED_DATE = tNP_CX_PROFILE_CREATED_DATE;
	}
	public String getTNP_CX_PROFILE_MODIFIED_BY() {
		return TNP_CX_PROFILE_MODIFIED_BY;
	}
	public void setTNP_CX_PROFILE_MODIFIED_BY(String tNP_CX_PROFILE_MODIFIED_BY) {
		TNP_CX_PROFILE_MODIFIED_BY = tNP_CX_PROFILE_MODIFIED_BY;
	}
	public String getTNP_CX_PROFILE_MODIFIED_DATE() {
		return TNP_CX_PROFILE_MODIFIED_DATE;
	}
	public void setTNP_CX_PROFILE_MODIFIED_DATE(String tNP_CX_PROFILE_MODIFIED_DATE) {
		TNP_CX_PROFILE_MODIFIED_DATE = tNP_CX_PROFILE_MODIFIED_DATE;
	}
	public String getTNP_CX_PROFILE_MODIFIED_COMMENT() {
		return TNP_CX_PROFILE_MODIFIED_COMMENT;
	}
	public void setTNP_CX_PROFILE_MODIFIED_COMMENT(String tNP_CX_PROFILE_MODIFIED_COMMENT) {
		TNP_CX_PROFILE_MODIFIED_COMMENT = tNP_CX_PROFILE_MODIFIED_COMMENT;
	}
	public String getTNP_CX_PROFILE_STATUS() {
		return TNP_CX_PROFILE_STATUS;
	}
	public void setTNP_CX_PROFILE_STATUS(String tNP_CX_PROFILE_STATUS) {
		TNP_CX_PROFILE_STATUS = tNP_CX_PROFILE_STATUS;
	}
	public String getTNP_CX_PROFILE_MOBILE_NUMBER() {
		return TNP_CX_PROFILE_MOBILE_NUMBER;
	}
	public void setTNP_CX_PROFILE_MOBILE_NUMBER(String tNP_CX_PROFILE_MOBILE_NUMBER) {
		TNP_CX_PROFILE_MOBILE_NUMBER = tNP_CX_PROFILE_MOBILE_NUMBER;
	}
	public String getTNP_CX_PROFILE_NAME() {
		return TNP_CX_PROFILE_NAME;
	}
	public void setTNP_CX_PROFILE_NAME(String tNP_CX_PROFILE_NAME) {
		TNP_CX_PROFILE_NAME = tNP_CX_PROFILE_NAME;
	}
	public String getTNP_CX_PROFILE_DATE_OF_BIRTH() {
		return TNP_CX_PROFILE_DATE_OF_BIRTH;
	}
	public void setTNP_CX_PROFILE_DATE_OF_BIRTH(String tNP_CX_PROFILE_DATE_OF_BIRTH) {
		TNP_CX_PROFILE_DATE_OF_BIRTH = tNP_CX_PROFILE_DATE_OF_BIRTH;
	}
	public String getTNP_CX_PROFILE_GENDER() {
		return TNP_CX_PROFILE_GENDER;
	}
	public void setTNP_CX_PROFILE_GENDER(String tNP_CX_PROFILE_GENDER) {
		TNP_CX_PROFILE_GENDER = tNP_CX_PROFILE_GENDER;
	}
	public String getTNP_CX_PROFILE_NATIONALITY() {
		return TNP_CX_PROFILE_NATIONALITY;
	}
	public void setTNP_CX_PROFILE_NATIONALITY(String tNP_CX_PROFILE_NATIONALITY) {
		TNP_CX_PROFILE_NATIONALITY = tNP_CX_PROFILE_NATIONALITY;
	}
	
	public String getTNP_CX_PROFILE_ID_TYPE() {
		return TNP_CX_PROFILE_ID_TYPE;
	}
	public void setTNP_CX_PROFILE_ID_TYPE(String tNP_CX_PROFILE_ID_TYPE) {
		TNP_CX_PROFILE_ID_TYPE = tNP_CX_PROFILE_ID_TYPE;
	}
	public String getTNP_CX_PROFILE_TIN_NO() {
		return TNP_CX_PROFILE_TIN_NO;
	}
	public void setTNP_CX_PROFILE_TIN_NO(String tNP_CX_PROFILE_TIN_NO) {
		TNP_CX_PROFILE_TIN_NO = tNP_CX_PROFILE_TIN_NO;
	}
	public String getTNP_CX_PROFILE_EMAIL_ID() {
		return TNP_CX_PROFILE_EMAIL_ID;
	}
	public void setTNP_CX_PROFILE_EMAIL_ID(String tNP_CX_PROFILE_EMAIL_ID) {
		TNP_CX_PROFILE_EMAIL_ID = tNP_CX_PROFILE_EMAIL_ID;
	}
	public String getTNP_CX_PROFILE_OTHER_CONTACT_NO() {
		return TNP_CX_PROFILE_OTHER_CONTACT_NO;
	}
	public void setTNP_CX_PROFILE_OTHER_CONTACT_NO(String tNP_CX_PROFILE_OTHER_CONTACT_NO) {
		TNP_CX_PROFILE_OTHER_CONTACT_NO = tNP_CX_PROFILE_OTHER_CONTACT_NO;
	}
	public String getTNP_CX_PROFILE_EMERGENCY_CONTACT_NO() {
		return TNP_CX_PROFILE_EMERGENCY_CONTACT_NO;
	}
	public void setTNP_CX_PROFILE_EMERGENCY_CONTACT_NO(String tNP_CX_PROFILE_EMERGENCY_CONTACT_NO) {
		TNP_CX_PROFILE_EMERGENCY_CONTACT_NO = tNP_CX_PROFILE_EMERGENCY_CONTACT_NO;
	}
	public String getTNP_CX_PROFILE_PROFESSION() {
		return TNP_CX_PROFILE_PROFESSION;
	}
	public void setTNP_CX_PROFILE_PROFESSION(String tNP_CX_PROFILE_PROFESSION) {
		TNP_CX_PROFILE_PROFESSION = tNP_CX_PROFILE_PROFESSION;
	}
	public String getTNP_CX_PROFILE_FATHER_NAME() {
		return TNP_CX_PROFILE_FATHER_NAME;
	}
	public void setTNP_CX_PROFILE_FATHER_NAME(String tNP_CX_PROFILE_FATHER_NAME) {
		TNP_CX_PROFILE_FATHER_NAME = tNP_CX_PROFILE_FATHER_NAME;
	}
	public String getTNP_CX_PROFILE_MOTHER_NAME() {
		return TNP_CX_PROFILE_MOTHER_NAME;
	}
	public void setTNP_CX_PROFILE_MOTHER_NAME(String tNP_CX_PROFILE_MOTHER_NAME) {
		TNP_CX_PROFILE_MOTHER_NAME = tNP_CX_PROFILE_MOTHER_NAME;
	}
	public String getTNP_CX_PROFILE_SPOUSE_NAME() {
		return TNP_CX_PROFILE_SPOUSE_NAME;
	}
	public void setTNP_CX_PROFILE_SPOUSE_NAME(String tNP_CX_PROFILE_SPOUSE_NAME) {
		TNP_CX_PROFILE_SPOUSE_NAME = tNP_CX_PROFILE_SPOUSE_NAME;
	}
	public String getTNP_CX_PROFILE_PERMANENT_ADDRESS_HOUSE_NO() {
		return TNP_CX_PROFILE_PERMANENT_ADDRESS_HOUSE_NO;
	}
	public void setTNP_CX_PROFILE_PERMANENT_ADDRESS_HOUSE_NO(String tNP_CX_PROFILE_PERMANENT_ADDRESS_HOUSE_NO) {
		TNP_CX_PROFILE_PERMANENT_ADDRESS_HOUSE_NO = tNP_CX_PROFILE_PERMANENT_ADDRESS_HOUSE_NO;
	}
	public String getTNP_CX_PROFILE_PERMANENT_ADDRESS_STREET() {
		return TNP_CX_PROFILE_PERMANENT_ADDRESS_STREET;
	}
	public void setTNP_CX_PROFILE_PERMANENT_ADDRESS_STREET(String tNP_CX_PROFILE_PERMANENT_ADDRESS_STREET) {
		TNP_CX_PROFILE_PERMANENT_ADDRESS_STREET = tNP_CX_PROFILE_PERMANENT_ADDRESS_STREET;
	}
	public String getTNP_CX_PROFILE_PERMANENT_ADDRESS_CITY() {
		return TNP_CX_PROFILE_PERMANENT_ADDRESS_CITY;
	}
	public void setTNP_CX_PROFILE_PERMANENT_ADDRESS_CITY(String tNP_CX_PROFILE_PERMANENT_ADDRESS_CITY) {
		TNP_CX_PROFILE_PERMANENT_ADDRESS_CITY = tNP_CX_PROFILE_PERMANENT_ADDRESS_CITY;
	}
	public String getTNP_CX_PROFILE_PERMANENT_ADDRESS_STATE() {
		return TNP_CX_PROFILE_PERMANENT_ADDRESS_STATE;
	}
	public void setTNP_CX_PROFILE_PERMANENT_ADDRESS_STATE(String tNP_CX_PROFILE_PERMANENT_ADDRESS_STATE) {
		TNP_CX_PROFILE_PERMANENT_ADDRESS_STATE = tNP_CX_PROFILE_PERMANENT_ADDRESS_STATE;
	}
	public String getTNP_CX_PROFILE_PERMANENT_ADDRESS_DISTRICT() {
		return TNP_CX_PROFILE_PERMANENT_ADDRESS_DISTRICT;
	}
	public void setTNP_CX_PROFILE_PERMANENT_ADDRESS_DISTRICT(String tNP_CX_PROFILE_PERMANENT_ADDRESS_DISTRICT) {
		TNP_CX_PROFILE_PERMANENT_ADDRESS_DISTRICT = tNP_CX_PROFILE_PERMANENT_ADDRESS_DISTRICT;
	}
	public String getTNP_CX_PROFILE_PERMANENT_ADDRESS_THANA() {
		return TNP_CX_PROFILE_PERMANENT_ADDRESS_THANA;
	}
	public void setTNP_CX_PROFILE_PERMANENT_ADDRESS_THANA(String tNP_CX_PROFILE_PERMANENT_ADDRESS_THANA) {
		TNP_CX_PROFILE_PERMANENT_ADDRESS_THANA = tNP_CX_PROFILE_PERMANENT_ADDRESS_THANA;
	}
	public String getTNP_CX_PROFILE_PERMANENT_ADDRESS_UNION() {
		return TNP_CX_PROFILE_PERMANENT_ADDRESS_UNION;
	}
	public void setTNP_CX_PROFILE_PERMANENT_ADDRESS_UNION(String tNP_CX_PROFILE_PERMANENT_ADDRESS_UNION) {
		TNP_CX_PROFILE_PERMANENT_ADDRESS_UNION = tNP_CX_PROFILE_PERMANENT_ADDRESS_UNION;
	}
	public String getTNP_CX_PROFILE_PERMANENT_ADDRESS_DIVISION() {
		return TNP_CX_PROFILE_PERMANENT_ADDRESS_DIVISION;
	}
	public void setTNP_CX_PROFILE_PERMANENT_ADDRESS_DIVISION(String tNP_CX_PROFILE_PERMANENT_ADDRESS_DIVISION) {
		TNP_CX_PROFILE_PERMANENT_ADDRESS_DIVISION = tNP_CX_PROFILE_PERMANENT_ADDRESS_DIVISION;
	}
	public String getTNP_CX_PROFILE_PERMANENT_ADDRESS_POSTCODE() {
		return TNP_CX_PROFILE_PERMANENT_ADDRESS_POSTCODE;
	}
	public void setTNP_CX_PROFILE_PERMANENT_ADDRESS_POSTCODE(String tNP_CX_PROFILE_PERMANENT_ADDRESS_POSTCODE) {
		TNP_CX_PROFILE_PERMANENT_ADDRESS_POSTCODE = tNP_CX_PROFILE_PERMANENT_ADDRESS_POSTCODE;
	}
	public String getTNP_CX_PROFILE_MAILING_ADDRESS_HOUSE_NO() {
		return TNP_CX_PROFILE_MAILING_ADDRESS_HOUSE_NO;
	}
	public void setTNP_CX_PROFILE_MAILING_ADDRESS_HOUSE_NO(String tNP_CX_PROFILE_MAILING_ADDRESS_HOUSE_NO) {
		TNP_CX_PROFILE_MAILING_ADDRESS_HOUSE_NO = tNP_CX_PROFILE_MAILING_ADDRESS_HOUSE_NO;
	}
	public String getTNP_CX_PROFILE_MAILING_ADDRESS_STREET() {
		return TNP_CX_PROFILE_MAILING_ADDRESS_STREET;
	}
	public void setTNP_CX_PROFILE_MAILING_ADDRESS_STREET(String tNP_CX_PROFILE_MAILING_ADDRESS_STREET) {
		TNP_CX_PROFILE_MAILING_ADDRESS_STREET = tNP_CX_PROFILE_MAILING_ADDRESS_STREET;
	}
	public String getTNP_CX_PROFILE_MAILING_ADDRESS_CITY() {
		return TNP_CX_PROFILE_MAILING_ADDRESS_CITY;
	}
	public void setTNP_CX_PROFILE_MAILING_ADDRESS_CITY(String tNP_CX_PROFILE_MAILING_ADDRESS_CITY) {
		TNP_CX_PROFILE_MAILING_ADDRESS_CITY = tNP_CX_PROFILE_MAILING_ADDRESS_CITY;
	}
	public String getTNP_CX_PROFILE_MAILING_ADDRESS_STATE() {
		return TNP_CX_PROFILE_MAILING_ADDRESS_STATE;
	}
	public void setTNP_CX_PROFILE_MAILING_ADDRESS_STATE(String tNP_CX_PROFILE_MAILING_ADDRESS_STATE) {
		TNP_CX_PROFILE_MAILING_ADDRESS_STATE = tNP_CX_PROFILE_MAILING_ADDRESS_STATE;
	}
	public String getTNP_CX_PROFILE_MAILING_ADDRESS_DISTRICT() {
		return TNP_CX_PROFILE_MAILING_ADDRESS_DISTRICT;
	}
	public void setTNP_CX_PROFILE_MAILING_ADDRESS_DISTRICT(String tNP_CX_PROFILE_MAILING_ADDRESS_DISTRICT) {
		TNP_CX_PROFILE_MAILING_ADDRESS_DISTRICT = tNP_CX_PROFILE_MAILING_ADDRESS_DISTRICT;
	}
	public String getTNP_CX_PROFILE_MAILING_ADDRESS_THANA() {
		return TNP_CX_PROFILE_MAILING_ADDRESS_THANA;
	}
	public void setTNP_CX_PROFILE_MAILING_ADDRESS_THANA(String tNP_CX_PROFILE_MAILING_ADDRESS_THANA) {
		TNP_CX_PROFILE_MAILING_ADDRESS_THANA = tNP_CX_PROFILE_MAILING_ADDRESS_THANA;
	}
	public String getTNP_CX_PROFILE_MAILING_ADDRESS_UNION() {
		return TNP_CX_PROFILE_MAILING_ADDRESS_UNION;
	}
	public void setTNP_CX_PROFILE_MAILING_ADDRESS_UNION(String tNP_CX_PROFILE_MAILING_ADDRESS_UNION) {
		TNP_CX_PROFILE_MAILING_ADDRESS_UNION = tNP_CX_PROFILE_MAILING_ADDRESS_UNION;
	}
	public String getTNP_CX_PROFILE_MAILING_ADDRESS_DIVISION() {
		return TNP_CX_PROFILE_MAILING_ADDRESS_DIVISION;
	}
	public void setTNP_CX_PROFILE_MAILING_ADDRESS_DIVISION(String tNP_CX_PROFILE_MAILING_ADDRESS_DIVISION) {
		TNP_CX_PROFILE_MAILING_ADDRESS_DIVISION = tNP_CX_PROFILE_MAILING_ADDRESS_DIVISION;
	}
	public String getTNP_CX_PROFILE_MAILING_ADDRESS_POSTCODE() {
		return TNP_CX_PROFILE_MAILING_ADDRESS_POSTCODE;
	}
	public void setTNP_CX_PROFILE_MAILING_ADDRESS_POSTCODE(String tNP_CX_PROFILE_MAILING_ADDRESS_POSTCODE) {
		TNP_CX_PROFILE_MAILING_ADDRESS_POSTCODE = tNP_CX_PROFILE_MAILING_ADDRESS_POSTCODE;
	}
	public String getTNP_CX_PROFILE_PURPOSE_OF_TRANSACTIONS() {
		return TNP_CX_PROFILE_PURPOSE_OF_TRANSACTIONS;
	}
	public void setTNP_CX_PROFILE_PURPOSE_OF_TRANSACTIONS(String tNP_CX_PROFILE_PURPOSE_OF_TRANSACTIONS) {
		TNP_CX_PROFILE_PURPOSE_OF_TRANSACTIONS = tNP_CX_PROFILE_PURPOSE_OF_TRANSACTIONS;
	}
	public String getTNP_CX_PROFILE_BANK_ACC_NO() {
		return TNP_CX_PROFILE_BANK_ACC_NO;
	}
	public void setTNP_CX_PROFILE_BANK_ACC_NO(String tNP_CX_PROFILE_BANK_ACC_NO) {
		TNP_CX_PROFILE_BANK_ACC_NO = tNP_CX_PROFILE_BANK_ACC_NO;
	}
	public String getTNP_CX_PROFILE_BANK_ACC_NAME() {
		return TNP_CX_PROFILE_BANK_ACC_NAME;
	}
	public void setTNP_CX_PROFILE_BANK_ACC_NAME(String tNP_CX_PROFILE_BANK_ACC_NAME) {
		TNP_CX_PROFILE_BANK_ACC_NAME = tNP_CX_PROFILE_BANK_ACC_NAME;
	}
	public String getTNP_CX_PROFILE_BANK_NAME() {
		return TNP_CX_PROFILE_BANK_NAME;
	}
	public void setTNP_CX_PROFILE_BANK_NAME(String tNP_CX_PROFILE_BANK_NAME) {
		TNP_CX_PROFILE_BANK_NAME = tNP_CX_PROFILE_BANK_NAME;
	}
	public String getTNP_CX_PROFILE_BANK_BRANCH() {
		return TNP_CX_PROFILE_BANK_BRANCH;
	}
	public void setTNP_CX_PROFILE_BANK_BRANCH(String tNP_CX_PROFILE_BANK_BRANCH) {
		TNP_CX_PROFILE_BANK_BRANCH = tNP_CX_PROFILE_BANK_BRANCH;
	}
	public String getTNP_CX_PROFILE_NOMINEE_NAME() {
		return TNP_CX_PROFILE_NOMINEE_NAME;
	}
	public void setTNP_CX_PROFILE_NOMINEE_NAME(String tNP_CX_PROFILE_NOMINEE_NAME) {
		TNP_CX_PROFILE_NOMINEE_NAME = tNP_CX_PROFILE_NOMINEE_NAME;
	}
	public String getTNP_CX_PROFILE_NOMINEE_RELATION() {
		return TNP_CX_PROFILE_NOMINEE_RELATION;
	}
	public void setTNP_CX_PROFILE_NOMINEE_RELATION(String tNP_CX_PROFILE_NOMINEE_RELATION) {
		TNP_CX_PROFILE_NOMINEE_RELATION = tNP_CX_PROFILE_NOMINEE_RELATION;
	}
	public String getTNP_CX_PROFILE_NOMINEE_CONTACT_NO() {
		return TNP_CX_PROFILE_NOMINEE_CONTACT_NO;
	}
	public void setTNP_CX_PROFILE_NOMINEE_CONTACT_NO(String tNP_CX_PROFILE_NOMINEE_CONTACT_NO) {
		TNP_CX_PROFILE_NOMINEE_CONTACT_NO = tNP_CX_PROFILE_NOMINEE_CONTACT_NO;
	}
	public String getTNP_CX_PROFILE_NOMINEE_FATHERS_NAME() {
		return TNP_CX_PROFILE_NOMINEE_FATHERS_NAME;
	}
	public void setTNP_CX_PROFILE_NOMINEE_FATHERS_NAME(String tNP_CX_PROFILE_NOMINEE_FATHERS_NAME) {
		TNP_CX_PROFILE_NOMINEE_FATHERS_NAME = tNP_CX_PROFILE_NOMINEE_FATHERS_NAME;
	}
	public String getTNP_CX_PROFILE_NOMINEE_MOTHERS_NAME() {
		return TNP_CX_PROFILE_NOMINEE_MOTHERS_NAME;
	}
	public void setTNP_CX_PROFILE_NOMINEE_MOTHERS_NAME(String tNP_CX_PROFILE_NOMINEE_MOTHERS_NAME) {
		TNP_CX_PROFILE_NOMINEE_MOTHERS_NAME = tNP_CX_PROFILE_NOMINEE_MOTHERS_NAME;
	}
	public String getTNP_CX_PROFILE_NOMINEE_ID_TYPE() {
		return TNP_CX_PROFILE_NOMINEE_ID_TYPE;
	}
	public void setTNP_CX_PROFILE_NOMINEE_ID_TYPE(String tNP_CX_PROFILE_NOMINEE_ID_TYPE) {
		TNP_CX_PROFILE_NOMINEE_ID_TYPE = tNP_CX_PROFILE_NOMINEE_ID_TYPE;
	}
	
	public String getTNP_CX_PROFILE_NOMINEE_ADDRESS_HOUSE_NO() {
		return TNP_CX_PROFILE_NOMINEE_ADDRESS_HOUSE_NO;
	}
	public void setTNP_CX_PROFILE_NOMINEE_ADDRESS_HOUSE_NO(String tNP_CX_PROFILE_NOMINEE_ADDRESS_HOUSE_NO) {
		TNP_CX_PROFILE_NOMINEE_ADDRESS_HOUSE_NO = tNP_CX_PROFILE_NOMINEE_ADDRESS_HOUSE_NO;
	}
	public String getTNP_CX_PROFILE_NOMINEE_ADDRESS_STEET() {
		return TNP_CX_PROFILE_NOMINEE_ADDRESS_STEET;
	}
	public void setTNP_CX_PROFILE_NOMINEE_ADDRESS_STEET(String tNP_CX_PROFILE_NOMINEE_ADDRESS_STEET) {
		TNP_CX_PROFILE_NOMINEE_ADDRESS_STEET = tNP_CX_PROFILE_NOMINEE_ADDRESS_STEET;
	}
	public String getTNP_CX_PROFILE_NOMINEE_ADDRESS_CITY() {
		return TNP_CX_PROFILE_NOMINEE_ADDRESS_CITY;
	}
	public void setTNP_CX_PROFILE_NOMINEE_ADDRESS_CITY(String tNP_CX_PROFILE_NOMINEE_ADDRESS_CITY) {
		TNP_CX_PROFILE_NOMINEE_ADDRESS_CITY = tNP_CX_PROFILE_NOMINEE_ADDRESS_CITY;
	}
	public String getTNP_CX_PROFILE_NOMINEE_ADDRESS_STATE() {
		return TNP_CX_PROFILE_NOMINEE_ADDRESS_STATE;
	}
	public void setTNP_CX_PROFILE_NOMINEE_ADDRESS_STATE(String tNP_CX_PROFILE_NOMINEE_ADDRESS_STATE) {
		TNP_CX_PROFILE_NOMINEE_ADDRESS_STATE = tNP_CX_PROFILE_NOMINEE_ADDRESS_STATE;
	}
	public String getTNP_CX_PROFILE_NOMINEE_DISTRICT() {
		return TNP_CX_PROFILE_NOMINEE_DISTRICT;
	}
	public void setTNP_CX_PROFILE_NOMINEE_DISTRICT(String tNP_CX_PROFILE_NOMINEE_DISTRICT) {
		TNP_CX_PROFILE_NOMINEE_DISTRICT = tNP_CX_PROFILE_NOMINEE_DISTRICT;
	}
	public String getTNP_CX_PROFILE_NOMINEE_THANA() {
		return TNP_CX_PROFILE_NOMINEE_THANA;
	}
	public void setTNP_CX_PROFILE_NOMINEE_THANA(String tNP_CX_PROFILE_NOMINEE_THANA) {
		TNP_CX_PROFILE_NOMINEE_THANA = tNP_CX_PROFILE_NOMINEE_THANA;
	}
	public String getTNP_CX_PROFILE_NOMINEE_UNION() {
		return TNP_CX_PROFILE_NOMINEE_UNION;
	}
	public void setTNP_CX_PROFILE_NOMINEE_UNION(String tNP_CX_PROFILE_NOMINEE_UNION) {
		TNP_CX_PROFILE_NOMINEE_UNION = tNP_CX_PROFILE_NOMINEE_UNION;
	}
	public String getTNP_CX_PROFILE_NOMINEE_DIVISION() {
		return TNP_CX_PROFILE_NOMINEE_DIVISION;
	}
	public void setTNP_CX_PROFILE_NOMINEE_DIVISION(String tNP_CX_PROFILE_NOMINEE_DIVISION) {
		TNP_CX_PROFILE_NOMINEE_DIVISION = tNP_CX_PROFILE_NOMINEE_DIVISION;
	}
	public String getTNP_CX_PROFILE_NOMINEE_POSTCODE() {
		return TNP_CX_PROFILE_NOMINEE_POSTCODE;
	}
	public void setTNP_CX_PROFILE_NOMINEE_POSTCODE(String tNP_CX_PROFILE_NOMINEE_POSTCODE) {
		TNP_CX_PROFILE_NOMINEE_POSTCODE = tNP_CX_PROFILE_NOMINEE_POSTCODE;
	}
	public String getTNP_CX_PROFILE_INTRODUCER_ID() {
		return TNP_CX_PROFILE_INTRODUCER_ID;
	}
	public void setTNP_CX_PROFILE_INTRODUCER_ID(String tNP_CX_PROFILE_INTRODUCER_ID) {
		TNP_CX_PROFILE_INTRODUCER_ID = tNP_CX_PROFILE_INTRODUCER_ID;
	}
	public String getTNP_CX_PROFILE_INTRODUCER_NAME() {
		return TNP_CX_PROFILE_INTRODUCER_NAME;
	}
	public void setTNP_CX_PROFILE_INTRODUCER_NAME(String tNP_CX_PROFILE_INTRODUCER_NAME) {
		TNP_CX_PROFILE_INTRODUCER_NAME = tNP_CX_PROFILE_INTRODUCER_NAME;
	}
	public String getTNP_CX_PROFILE_INTRODUCER_BRANCH_NAME() {
		return TNP_CX_PROFILE_INTRODUCER_BRANCH_NAME;
	}
	public void setTNP_CX_PROFILE_INTRODUCER_BRANCH_NAME(String tNP_CX_PROFILE_INTRODUCER_BRANCH_NAME) {
		TNP_CX_PROFILE_INTRODUCER_BRANCH_NAME = tNP_CX_PROFILE_INTRODUCER_BRANCH_NAME;
	}
	public String getTNP_CX_PROFILE_INTRODUCER_MOBILE_NUM() {
		return TNP_CX_PROFILE_INTRODUCER_MOBILE_NUM;
	}
	public void setTNP_CX_PROFILE_INTRODUCER_MOBILE_NUM(String tNP_CX_PROFILE_INTRODUCER_MOBILE_NUM) {
		TNP_CX_PROFILE_INTRODUCER_MOBILE_NUM = tNP_CX_PROFILE_INTRODUCER_MOBILE_NUM;
	}
	public String getTNP_CX_PROFILE_INTRODUCER_HOME_NO() {
		return TNP_CX_PROFILE_INTRODUCER_HOME_NO;
	}
	public void setTNP_CX_PROFILE_INTRODUCER_HOME_NO(String tNP_CX_PROFILE_INTRODUCER_HOME_NO) {
		TNP_CX_PROFILE_INTRODUCER_HOME_NO = tNP_CX_PROFILE_INTRODUCER_HOME_NO;
	}
	public String getTNP_CX_PROFILE_INTRODUCER_CITY() {
		return TNP_CX_PROFILE_INTRODUCER_CITY;
	}
	public void setTNP_CX_PROFILE_INTRODUCER_CITY(String tNP_CX_PROFILE_INTRODUCER_CITY) {
		TNP_CX_PROFILE_INTRODUCER_CITY = tNP_CX_PROFILE_INTRODUCER_CITY;
	}
	public String getTNP_CX_PROFILE_INTRODUCER_STREET() {
		return TNP_CX_PROFILE_INTRODUCER_STREET;
	}
	public void setTNP_CX_PROFILE_INTRODUCER_STREET(String tNP_CX_PROFILE_INTRODUCER_STREET) {
		TNP_CX_PROFILE_INTRODUCER_STREET = tNP_CX_PROFILE_INTRODUCER_STREET;
	}
	public String getTNP_CX_PROFILE_INTRODUCER_STATE() {
		return TNP_CX_PROFILE_INTRODUCER_STATE;
	}
	public void setTNP_CX_PROFILE_INTRODUCER_STATE(String tNP_CX_PROFILE_INTRODUCER_STATE) {
		TNP_CX_PROFILE_INTRODUCER_STATE = tNP_CX_PROFILE_INTRODUCER_STATE;
	}
	public String getTNP_CX_PROFILE_INTRODUCER_DISTRICT() {
		return TNP_CX_PROFILE_INTRODUCER_DISTRICT;
	}
	public void setTNP_CX_PROFILE_INTRODUCER_DISTRICT(String tNP_CX_PROFILE_INTRODUCER_DISTRICT) {
		TNP_CX_PROFILE_INTRODUCER_DISTRICT = tNP_CX_PROFILE_INTRODUCER_DISTRICT;
	}
	public String getTNP_CX_PROFILE_INTRODUCER_THANA() {
		return TNP_CX_PROFILE_INTRODUCER_THANA;
	}
	public void setTNP_CX_PROFILE_INTRODUCER_THANA(String tNP_CX_PROFILE_INTRODUCER_THANA) {
		TNP_CX_PROFILE_INTRODUCER_THANA = tNP_CX_PROFILE_INTRODUCER_THANA;
	}
	public String getTNP_CX_PROFILE_INTRODUCER_UNION() {
		return TNP_CX_PROFILE_INTRODUCER_UNION;
	}
	public void setTNP_CX_PROFILE_INTRODUCER_UNION(String tNP_CX_PROFILE_INTRODUCER_UNION) {
		TNP_CX_PROFILE_INTRODUCER_UNION = tNP_CX_PROFILE_INTRODUCER_UNION;
	}
	public String getTNP_CX_PROFILE_VERIFIED_USER() {
		return TNP_CX_PROFILE_VERIFIED_USER;
	}
	public void setTNP_CX_PROFILE_VERIFIED_USER(String tNP_CX_PROFILE_VERIFIED_USER) {
		TNP_CX_PROFILE_VERIFIED_USER = tNP_CX_PROFILE_VERIFIED_USER;
	}
	public String getTNP_CX_PROFILE_APPROVAL_STATUS() {
		return TNP_CX_PROFILE_APPROVAL_STATUS;
	}
	public void setTNP_CX_PROFILE_APPROVAL_STATUS(String tNP_CX_PROFILE_APPROVAL_STATUS) {
		TNP_CX_PROFILE_APPROVAL_STATUS = tNP_CX_PROFILE_APPROVAL_STATUS;
	}
	public String getTNP_CX_PROFILE_APPROVAL_COMMENTS() {
		return TNP_CX_PROFILE_APPROVAL_COMMENTS;
	}
	public void setTNP_CX_PROFILE_APPROVAL_COMMENTS(String tNP_CX_PROFILE_APPROVAL_COMMENTS) {
		TNP_CX_PROFILE_APPROVAL_COMMENTS = tNP_CX_PROFILE_APPROVAL_COMMENTS;
	}
	public String getTNP_CX_PROFILE_REFERANCE_NO_OTHER() {
		return TNP_CX_PROFILE_REFERANCE_NO_OTHER;
	}
	public void setTNP_CX_PROFILE_REFERANCE_NO_OTHER(String tNP_CX_PROFILE_REFERANCE_NO_OTHER) {
		TNP_CX_PROFILE_REFERANCE_NO_OTHER = tNP_CX_PROFILE_REFERANCE_NO_OTHER;
	}
	public String getTNP_CX_PROFILE_VERIFIED_IMG_NIC() {
		return TNP_CX_PROFILE_VERIFIED_IMG_NIC;
	}
	public void setTNP_CX_PROFILE_VERIFIED_IMG_NIC(String tNP_CX_PROFILE_VERIFIED_IMG_NIC) {
		TNP_CX_PROFILE_VERIFIED_IMG_NIC = tNP_CX_PROFILE_VERIFIED_IMG_NIC;
	}
	public String getTNP_CX_PROFILE_VERIFIED_IMG_PHOTO() {
		return TNP_CX_PROFILE_VERIFIED_IMG_PHOTO;
	}
	public void setTNP_CX_PROFILE_VERIFIED_IMG_PHOTO(String tNP_CX_PROFILE_VERIFIED_IMG_PHOTO) {
		TNP_CX_PROFILE_VERIFIED_IMG_PHOTO = tNP_CX_PROFILE_VERIFIED_IMG_PHOTO;
	}
	public String getTNP_CX_PROFILE_VERIFIED_IMG_KYC_FORM() {
		return TNP_CX_PROFILE_VERIFIED_IMG_KYC_FORM;
	}
	public void setTNP_CX_PROFILE_VERIFIED_IMG_KYC_FORM(String tNP_CX_PROFILE_VERIFIED_IMG_KYC_FORM) {
		TNP_CX_PROFILE_VERIFIED_IMG_KYC_FORM = tNP_CX_PROFILE_VERIFIED_IMG_KYC_FORM;
	}
	
	public String getTNP_CX_PROFILE_VERIFIED_IMG_OTHER() {
		return TNP_CX_PROFILE_VERIFIED_IMG_OTHER;
	}
	public void setTNP_CX_PROFILE_VERIFIED_IMG_OTHER(String tNP_CX_PROFILE_VERIFIED_IMG_OTHER) {
		TNP_CX_PROFILE_VERIFIED_IMG_OTHER = tNP_CX_PROFILE_VERIFIED_IMG_OTHER;
	}
	public String getTNP_CX_PROFILE_INFO1() {
		return TNP_CX_PROFILE_INFO1;
	}
	public void setTNP_CX_PROFILE_INFO1(String tNP_CX_PROFILE_INFO1) {
		TNP_CX_PROFILE_INFO1 = tNP_CX_PROFILE_INFO1;
	}
	public String getTNP_CX_PROFILE_INFO2() {
		return TNP_CX_PROFILE_INFO2;
	}
	public void setTNP_CX_PROFILE_INFO2(String tNP_CX_PROFILE_INFO2) {
		TNP_CX_PROFILE_INFO2 = tNP_CX_PROFILE_INFO2;
	}
	public String getTNP_CX_PROFILE_INFO3() {
		return TNP_CX_PROFILE_INFO3;
	}
	public void setTNP_CX_PROFILE_INFO3(String tNP_CX_PROFILE_INFO3) {
		TNP_CX_PROFILE_INFO3 = tNP_CX_PROFILE_INFO3;
	}
	public String getTNP_CX_PROFILE_INFO4() {
		return TNP_CX_PROFILE_INFO4;
	}
	public void setTNP_CX_PROFILE_INFO4(String tNP_CX_PROFILE_INFO4) {
		TNP_CX_PROFILE_INFO4 = tNP_CX_PROFILE_INFO4;
	}
	public String getTNP_CX_PROFILE_INFO5() {
		return TNP_CX_PROFILE_INFO5;
	}
	public void setTNP_CX_PROFILE_INFO5(String tNP_CX_PROFILE_INFO5) {
		TNP_CX_PROFILE_INFO5 = tNP_CX_PROFILE_INFO5;
	}
	public String getTNP_CX_PROFILE_VERIFIED_IMG_TIN_FORM() {
		return TNP_CX_PROFILE_VERIFIED_IMG_TIN_FORM;
	}
	public void setTNP_CX_PROFILE_VERIFIED_IMG_TIN_FORM(String tNP_CX_PROFILE_VERIFIED_IMG_TIN_FORM) {
		TNP_CX_PROFILE_VERIFIED_IMG_TIN_FORM = tNP_CX_PROFILE_VERIFIED_IMG_TIN_FORM;
	}
	public String getTNP_CX_PROFILE_VERIFIED_CITIZENSHIP_CERITIFICATE_FROM() {
		return TNP_CX_PROFILE_VERIFIED_CITIZENSHIP_CERITIFICATE_FROM;
	}
	public void setTNP_CX_PROFILE_VERIFIED_CITIZENSHIP_CERITIFICATE_FROM(
			String tNP_CX_PROFILE_VERIFIED_CITIZENSHIP_CERITIFICATE_FROM) {
		TNP_CX_PROFILE_VERIFIED_CITIZENSHIP_CERITIFICATE_FROM = tNP_CX_PROFILE_VERIFIED_CITIZENSHIP_CERITIFICATE_FROM;
	}
	public String getTNP_CX_PROFILE_ID_NUMBER() {
		return TNP_CX_PROFILE_ID_NUMBER;
	}
	public void setTNP_CX_PROFILE_ID_NUMBER(String tNP_CX_PROFILE_ID_NUMBER) {
		TNP_CX_PROFILE_ID_NUMBER = tNP_CX_PROFILE_ID_NUMBER;
	}
	public String getTNP_CX_PROFILE_NOMINEE_ID_NUMBER() {
		return TNP_CX_PROFILE_NOMINEE_ID_NUMBER;
	}
	public void setTNP_CX_PROFILE_NOMINEE_ID_NUMBER(String tNP_CX_PROFILE_NOMINEE_ID_NUMBER) {
		TNP_CX_PROFILE_NOMINEE_ID_NUMBER = tNP_CX_PROFILE_NOMINEE_ID_NUMBER;
	}
	
	
	
	
}