package com.evidu.bank.entitiy;

public class AgentAPI {
	
	private String TNP_AG_PROFILE_UUID;                   
	private String TNP_AG_PROFILE_PARAENT_KYC_ID;  
	private String TNP_AG_PROFILE_OWNER_USER_TYPE;  
	private String kycFormNo;  
	private String TNP_AG_PROFILE_AGENT_TYPE;  
	private String TNP_AG_PROFILE_REF_NO;  
	private String TNP_AG_PROFILE_CREATED_BY;  
	private String TNP_AG_PROFILE_CREATED_BRANCH;  
	private String TNP_AG_PROFILE_CREATED_DATE;  
	private String TNP_AG_PROFILE_MODIFIED_BY;  
	private String TNP_AG_PROFILE_MODIFIED_DATE;  
	private String TNP_AG_PROFILE_MODIFIED_COMMENT;  
	private String TNP_AG_PROFILE_STATUS;  
	private String TNP_AG_PROFILE_COMPANY_MOBILE_NUMBER;  
	private String TNP_AG_PROFILE_COMPANY_NAME;  
	private String TNP_AG_PROFILE_COMPANY_REGION;  
	private String TNP_AG_PROFILE_COMPANY_AREA;  
	private String TNP_AG_PROFILE_COMPANY_TERRITORY;  
	private String TNP_AG_PROFILE_ORGANIZATION_NAME;  
	private String TNP_AG_PROFILE_ORGANIZATION_MOBILE;  
	private String TNP_AG_PROFILE_ORGANIZATION_ADDRESS_HOUSE_NO;  
	private String TNP_AG_PROFILE_ORGANIZATION_ADDRESS_STREET;  
	private String TNP_AG_PROFILE_ORGANIZATION_ADDRESS_CITY;  
	private String TNP_AG_PROFILE_ORGANIZATION_ADDRESS_STATE;  
	private String TNP_AG_PROFILE_ORGANIZATION_ADDRESS_THANA;  
	private String TNP_AG_PROFILE_ORGANIZATION_ADDRESS_DISTRICT;  
	private String TNP_AG_PROFILE_ORGANIZATION_ADDRESS_UNION;  
	private String TNP_AG_PROFILE_ORGANIZATION_ADDRESS_DIVISION;  
	private String TNP_AG_PROFILE_ORGANIZATION_ADDRESS_POSTCODE;  
	private String TNP_AG_PROFILE_COMPANY_BANK_ACC_NO;  
	private String TNP_AG_PROFILE_VAT_REG_NO;  
	private String TNP_AG_PROFILE_TIN_NO;  
	private String TNP_AG_PROFILE_ISSUING_AUTHORITY;  
	private String TNP_AG_PROFILE_OTHER_CONTACT_NO;  
	private String TNP_AG_PROFILE_COMPANY_BANK_ACC_NAME;  
	private String TNP_AG_PROFILE_COMPANY_BANK_NAME;  
	private String TNP_AG_PROFILE_COMPANY_BANK_BRANCH;  
	private String TNP_AG_PROFILE_NAME;  
	private String TNP_AG_PROFILE_DATE_OF_BIRTH;  
	private String TNP_AG_PROFILE_GENDER;  
	private String TNP_AG_PROFILE_NATIONALITY;  
	private String TNP_AG_PROFILE_ID_NUMBER;  
	private String TNP_AG_PROFILE_ID_TYPE;  
	private String TNP_AG_PROFILE_EMAIL_ID;  
	private String TNP_AG_PROFILE_TRADE_LICENSE_NO;  
	private String TNP_AG_PROFILE_EMERGENCY_CONTACT_NO;  
	private String TNP_AG_PROFILE_PROFESSION;  
	private String TNP_AG_PROFILE_FATHER_NAME;  
	private String TNP_AG_PROFILE_MOTHER_NAME;  
	private String TNP_AG_PROFILE_SPOUSE_NAME;  
	private String TNP_AG_PROFILE_PERMANENT_ADDRESS_HOUSE_NO;
	private String TNP_AG_PROFILE_PERMANENT_ADDRESS_STREET;  
	private String TNP_AG_PROFILE_PERMANENT_ADDRESS_CITY;  
	private String TNP_AG_PROFILE_PERMANENT_ADDRESS_STATE;  
	private String TNP_AG_PROFILE_PERMANENT_ADDRESS_DISTRICT;  
	private String TNP_AG_PROFILE_PERMANENT_ADDRESS_THANA;  
	private String TNP_AG_PROFILE_PERMANENT_ADDRESS_UNION;  
	private String TNP_AG_PROFILE_PERMANENT_ADDRESS_DIVISION;  
	private String TNP_AG_PROFILE_PERMANENT_ADDRESS_POSTCODE;  
	private String TNP_AG_PROFILE_BANK_ACC_NO;  
	private String TNP_AG_PROFILE_BANK_ACC_NAME;  
	private String TNP_AG_PROFILE_BANK_NAME;  
	private String TNP_AG_PROFILE_BANK_BRANCH;  
	private String TNP_AG_PROFILE_NOMINEE_NAME;  
	private String TNP_AG_PROFILE_NOMINEE_RELATION;  
	private String TNP_AG_PROFILE_NOMINEE_CONTACT_NO;  
	private String TNP_AG_PROFILE_NOMINEE_FATHERS_NAME;  
	private String TNP_AG_PROFILE_NOMINEE_MOTHERS_NAME;  
	private String TNP_AG_PROFILE_NOMINEE_ID_TYPE;  
	private String TNP_AG_PROFILE_NOMINEE_ID_NO;  
	private String TNP_AG_PROFILE_NOMINEE_ADDRESS_HOUSE_NO;  
	private String TNP_AG_PROFILE_NOMINEE_ADDRESS_STEET;  
	private String TNP_AG_PROFILE_NOMINEE_ADDRESS_CITY;  
	private String TNP_AG_PROFILE_NOMINEE_ADDRESS_STATE;  
	private String TNP_AG_PROFILE_NOMINEE_DISTRICT;  
	private String TNP_AG_PROFILE_NOMINEE_THANA;  
	private String TNP_AG_PROFILE_NOMINEE_UNION;  
	private String TNP_AG_PROFILE_NOMINEE_DIVISION;  
	private String TNP_AG_PROFILE_NOMINEE_POSTCODE;  
	private String TNP_AG_PROFILE_VERIFIED_USER;  
	private String TNP_AG_PROFILE_APPROVAL_STATUS;  
	private String TNP_AG_PROFILE_APPROVAL_COMMENTS;  
	private String TNP_AG_PROFILE_DSR_CODE;  
	private String TNP_AG_PROFILE_DSR_ROUTE;  
	private String TNP_AG_PROFILE_DSR_LIMIT;  
	private String TNP_AG_PROFILE_REFERANCE_NO_OTHER;  
	private String TNP_AG_PROFILE_VERIFIED_IMG_NIC;  
	private String TNP_AG_PROFILE_VERIFIED_IMG_PHOTO;  
	private String TNP_AG_PROFILE_VERIFIED_IMG_KYC_FORM;  
	private String TNP_AG_PROFILE_VERIFIED_IMG_UPDATED_KYC_FORM;  
	private String TNP_AG_PROFILE_VERIFIED_TIN;  
	private String TNP_AG_PROFILE_VERIFIED_TRADE_LICENSE;  
	private String TNP_AG_PROFILE_VERIFIED_VAT;  
	private String TNP_AG_PROFILE_VERIFIED_IMG_OTHER;  
	private String TNP_AG_PROFILE_INFO1;  
	private String TNP_AG_PROFILE_INFO2;  
	private String TNP_AG_PROFILE_INFO3;  
	private String TNP_AG_PROFILE_INFO4;  
	private String TNP_AG_PROFILE_INFO5;  
	private String TNP_AG_PROFILE_MID;  
	private String TNP_AG_PROFILE_INTRODUCER_NAME;  
	private String TNP_AG_PROFILE_INTRODUCER_MOBILE;  
	private String TNP_AG_PROFILE_INTRODUCER_OCCUPATION;  
	private String TNP_AG_PROFILE_INTRODUCER_HOUSE_NO;  
	private String TNP_AG_PROFILE_INTRODUCER_STREET;  
	private String TNP_AG_PROFILE_INTRODUCER_CITY;  
	private String TNP_AG_PROFILE_INTRODUCER_STATE;  
	private String TNP_AG_PROFILE_INTRODUCER_DISTRICT;  
	private String TNP_AG_PROFILE_INTRODUCER_THANA;  
	private String TNP_AG_PROFILE_INTRODUCER_UNION;  
	private String TNP_AG_PROFILE_INTRODUCER_DIVISION;  
	private String TNP_AG_PROFILE_INTRODUCER_POST_CODE;
	private String AgentRecordLockStatus;
	private String AgentRecordLockBy;
	private String TNP_AG_PROFILE_SUBMITTED_DATE;
	private String image1;
	private String image2;
	private String image3;
	private String image4;
	private String image5;
	private String image6;
	private String image7;
	private String image8;
	private String image9;
	private String image10;
	private int statusCode;
	private String statusMsg;
	private String requestId;
	
	private String TNP_AG_PROFILE_IMAGES_PROFILE_UUID;
	private String TNP_AG_PROFILE_IMAGES_PARENT_KYC_ID;
	private String TNP_AG_PROFILE_IMAGES_USER_TYPE;
	private String TNP_AG_PROFILE_IMAGES_KYC_NO;
	private String TNP_AG_PROFILE_IMAGES_NID;
	private String TNP_AG_PROFILE_IMAGES_PHOTO;
	private String TNP_AG_PROFILE_IMAGES_KYC_FORM;
	private String TNP_AG_PROFILE_IMAGES_TIN;
	private String TNP_AG_PROFILE_IMAGES_VAT; 
	private String TNP_AG_PROFILE_IMAGES_OWNERSHIP_FORM;
	private String TNP_AG_PROFILE_IMAGES_TRADE_LICENSE;
	private String TNP_AG_PROFILE_IMAGES_OTHER;
	private String TNP_AG_PROFILE_IMAGES_NOMINEE_PHOTO;
	private String TNP_AG_PROFILE_IMAGES_NOMINEE_NID;
	private String TNP_AG_PROFILE_IMAGES_RESOLUTION;
	private String TNP_AG_PROFILE_IMAGES_NGO_CERTIFICATE;
	private String TNP_AG_PROFILE_IMAGES_MRA_CERTIFICATE;
	private String TNP_AG_PROFILE_IMAGES_CITIZEN_CERTIFICATE;
	private String TNP_AG_PROFILE_IMAGES_NFO1;
	private String TNP_AG_PROFILE_IMAGES_NFO2;
	private String TNP_AG_PROFILE_IMAGES_NFO3; 
	private String TNP_AG_PROFILE_IMAGES_NFO4; 
	private String TNP_AG_PROFILE_IMAGES_NFO5;
	private String image_nid;
	private String image_photo;
	private String image_kyc;
	private String image_tin;
	private String image_vat;
	private String image_ownership;
	private String image_trade;
	private String image_nominee;
	private String image_nomineeId;
	private String image_other;
	private String lock_status;
	private String lock_by;
	private String lock_time;
	private String TNP_AG_PROFILE_IMAGES_STATUS;
	private String TNP_AG_PROFILE_IMAGES_BANK_STATUS;
	private String TNP_AG_PROFILE_IMAGES_BANK_MODIFY_DATE;
	private String TNP_AG_PROFILE_IMAGES_BANK_REJECT_REASON;
	private String TNP_AG_PROFILE_IMAGES_LOCK_STATUS;
	
	private String image_nid_path;
	private String image_photo_path;
	private String image_kyc_path;
	private String image_tin_path;
	private String image_vat_path;
	private String image_ownership_path;
	private String image_trade_path;
	private String image_other_path;
	private String TNP_AG_PROFILE_OWNERSHIP_TYPE;
	
	public String getTNP_AG_PROFILE_OWNERSHIP_TYPE() {
		return TNP_AG_PROFILE_OWNERSHIP_TYPE;
	}
	public void setTNP_AG_PROFILE_OWNERSHIP_TYPE(String tNP_AG_PROFILE_OWNERSHIP_TYPE) {
		TNP_AG_PROFILE_OWNERSHIP_TYPE = tNP_AG_PROFILE_OWNERSHIP_TYPE;
	}
	public String getTNP_AG_PROFILE_UUID() {
		return TNP_AG_PROFILE_UUID;
	}
	public void setTNP_AG_PROFILE_UUID(String tNP_AG_PROFILE_UUID) {
		TNP_AG_PROFILE_UUID = tNP_AG_PROFILE_UUID;
	}
	public String getTNP_AG_PROFILE_PARAENT_KYC_ID() {
		return TNP_AG_PROFILE_PARAENT_KYC_ID;
	}
	public void setTNP_AG_PROFILE_PARAENT_KYC_ID(String tNP_AG_PROFILE_PARAENT_KYC_ID) {
		TNP_AG_PROFILE_PARAENT_KYC_ID = tNP_AG_PROFILE_PARAENT_KYC_ID;
	}
	public String getTNP_AG_PROFILE_OWNER_USER_TYPE() {
		return TNP_AG_PROFILE_OWNER_USER_TYPE;
	}
	public void setTNP_AG_PROFILE_OWNER_USER_TYPE(String tNP_AG_PROFILE_OWNER_USER_TYPE) {
		TNP_AG_PROFILE_OWNER_USER_TYPE = tNP_AG_PROFILE_OWNER_USER_TYPE;
	}
	public String getKycFormNo() {
		return kycFormNo;
	}
	public void setKycFormNo(String kycFormNo) {
		this.kycFormNo = kycFormNo;
	}
	public String getTNP_AG_PROFILE_AGENT_TYPE() {
		return TNP_AG_PROFILE_AGENT_TYPE;
	}
	public void setTNP_AG_PROFILE_AGENT_TYPE(String tNP_AG_PROFILE_AGENT_TYPE) {
		TNP_AG_PROFILE_AGENT_TYPE = tNP_AG_PROFILE_AGENT_TYPE;
	}
	public String getTNP_AG_PROFILE_REF_NO() {
		return TNP_AG_PROFILE_REF_NO;
	}
	public void setTNP_AG_PROFILE_REF_NO(String tNP_AG_PROFILE_REF_NO) {
		TNP_AG_PROFILE_REF_NO = tNP_AG_PROFILE_REF_NO;
	}
	public String getTNP_AG_PROFILE_CREATED_BY() {
		return TNP_AG_PROFILE_CREATED_BY;
	}
	public void setTNP_AG_PROFILE_CREATED_BY(String tNP_AG_PROFILE_CREATED_BY) {
		TNP_AG_PROFILE_CREATED_BY = tNP_AG_PROFILE_CREATED_BY;
	}
	public String getTNP_AG_PROFILE_CREATED_BRANCH() {
		return TNP_AG_PROFILE_CREATED_BRANCH;
	}
	public void setTNP_AG_PROFILE_CREATED_BRANCH(String tNP_AG_PROFILE_CREATED_BRANCH) {
		TNP_AG_PROFILE_CREATED_BRANCH = tNP_AG_PROFILE_CREATED_BRANCH;
	}
	public String getTNP_AG_PROFILE_CREATED_DATE() {
		return TNP_AG_PROFILE_CREATED_DATE;
	}
	public void setTNP_AG_PROFILE_CREATED_DATE(String tNP_AG_PROFILE_CREATED_DATE) {
		TNP_AG_PROFILE_CREATED_DATE = tNP_AG_PROFILE_CREATED_DATE;
	}
	public String getTNP_AG_PROFILE_MODIFIED_BY() {
		return TNP_AG_PROFILE_MODIFIED_BY;
	}
	public void setTNP_AG_PROFILE_MODIFIED_BY(String tNP_AG_PROFILE_MODIFIED_BY) {
		TNP_AG_PROFILE_MODIFIED_BY = tNP_AG_PROFILE_MODIFIED_BY;
	}
	public String getTNP_AG_PROFILE_MODIFIED_DATE() {
		return TNP_AG_PROFILE_MODIFIED_DATE;
	}
	public void setTNP_AG_PROFILE_MODIFIED_DATE(String tNP_AG_PROFILE_MODIFIED_DATE) {
		TNP_AG_PROFILE_MODIFIED_DATE = tNP_AG_PROFILE_MODIFIED_DATE;
	}
	public String getTNP_AG_PROFILE_MODIFIED_COMMENT() {
		return TNP_AG_PROFILE_MODIFIED_COMMENT;
	}
	public void setTNP_AG_PROFILE_MODIFIED_COMMENT(String tNP_AG_PROFILE_MODIFIED_COMMENT) {
		TNP_AG_PROFILE_MODIFIED_COMMENT = tNP_AG_PROFILE_MODIFIED_COMMENT;
	}
	public String getTNP_AG_PROFILE_STATUS() {
		return TNP_AG_PROFILE_STATUS;
	}
	public void setTNP_AG_PROFILE_STATUS(String tNP_AG_PROFILE_STATUS) {
		TNP_AG_PROFILE_STATUS = tNP_AG_PROFILE_STATUS;
	}
	public String getTNP_AG_PROFILE_COMPANY_MOBILE_NUMBER() {
		return TNP_AG_PROFILE_COMPANY_MOBILE_NUMBER;
	}
	public void setTNP_AG_PROFILE_COMPANY_MOBILE_NUMBER(String tNP_AG_PROFILE_COMPANY_MOBILE_NUMBER) {
		TNP_AG_PROFILE_COMPANY_MOBILE_NUMBER = tNP_AG_PROFILE_COMPANY_MOBILE_NUMBER;
	}
	public String getTNP_AG_PROFILE_COMPANY_NAME() {
		return TNP_AG_PROFILE_COMPANY_NAME;
	}
	public void setTNP_AG_PROFILE_COMPANY_NAME(String tNP_AG_PROFILE_COMPANY_NAME) {
		TNP_AG_PROFILE_COMPANY_NAME = tNP_AG_PROFILE_COMPANY_NAME;
	}
	public String getTNP_AG_PROFILE_COMPANY_REGION() {
		return TNP_AG_PROFILE_COMPANY_REGION;
	}
	public void setTNP_AG_PROFILE_COMPANY_REGION(String tNP_AG_PROFILE_COMPANY_REGION) {
		TNP_AG_PROFILE_COMPANY_REGION = tNP_AG_PROFILE_COMPANY_REGION;
	}
	public String getTNP_AG_PROFILE_COMPANY_AREA() {
		return TNP_AG_PROFILE_COMPANY_AREA;
	}
	public void setTNP_AG_PROFILE_COMPANY_AREA(String tNP_AG_PROFILE_COMPANY_AREA) {
		TNP_AG_PROFILE_COMPANY_AREA = tNP_AG_PROFILE_COMPANY_AREA;
	}
	public String getTNP_AG_PROFILE_COMPANY_TERRITORY() {
		return TNP_AG_PROFILE_COMPANY_TERRITORY;
	}
	public void setTNP_AG_PROFILE_COMPANY_TERRITORY(String tNP_AG_PROFILE_COMPANY_TERRITORY) {
		TNP_AG_PROFILE_COMPANY_TERRITORY = tNP_AG_PROFILE_COMPANY_TERRITORY;
	}
	public String getTNP_AG_PROFILE_ORGANIZATION_NAME() {
		return TNP_AG_PROFILE_ORGANIZATION_NAME;
	}
	public void setTNP_AG_PROFILE_ORGANIZATION_NAME(String tNP_AG_PROFILE_ORGANIZATION_NAME) {
		TNP_AG_PROFILE_ORGANIZATION_NAME = tNP_AG_PROFILE_ORGANIZATION_NAME;
	}
	public String getTNP_AG_PROFILE_ORGANIZATION_MOBILE() {
		return TNP_AG_PROFILE_ORGANIZATION_MOBILE;
	}
	public void setTNP_AG_PROFILE_ORGANIZATION_MOBILE(String tNP_AG_PROFILE_ORGANIZATION_MOBILE) {
		TNP_AG_PROFILE_ORGANIZATION_MOBILE = tNP_AG_PROFILE_ORGANIZATION_MOBILE;
	}
	public String getTNP_AG_PROFILE_ORGANIZATION_ADDRESS_HOUSE_NO() {
		return TNP_AG_PROFILE_ORGANIZATION_ADDRESS_HOUSE_NO;
	}
	public void setTNP_AG_PROFILE_ORGANIZATION_ADDRESS_HOUSE_NO(String tNP_AG_PROFILE_ORGANIZATION_ADDRESS_HOUSE_NO) {
		TNP_AG_PROFILE_ORGANIZATION_ADDRESS_HOUSE_NO = tNP_AG_PROFILE_ORGANIZATION_ADDRESS_HOUSE_NO;
	}
	public String getTNP_AG_PROFILE_ORGANIZATION_ADDRESS_STREET() {
		return TNP_AG_PROFILE_ORGANIZATION_ADDRESS_STREET;
	}
	public void setTNP_AG_PROFILE_ORGANIZATION_ADDRESS_STREET(String tNP_AG_PROFILE_ORGANIZATION_ADDRESS_STREET) {
		TNP_AG_PROFILE_ORGANIZATION_ADDRESS_STREET = tNP_AG_PROFILE_ORGANIZATION_ADDRESS_STREET;
	}
	public String getTNP_AG_PROFILE_ORGANIZATION_ADDRESS_CITY() {
		return TNP_AG_PROFILE_ORGANIZATION_ADDRESS_CITY;
	}
	public void setTNP_AG_PROFILE_ORGANIZATION_ADDRESS_CITY(String tNP_AG_PROFILE_ORGANIZATION_ADDRESS_CITY) {
		TNP_AG_PROFILE_ORGANIZATION_ADDRESS_CITY = tNP_AG_PROFILE_ORGANIZATION_ADDRESS_CITY;
	}
	public String getTNP_AG_PROFILE_ORGANIZATION_ADDRESS_STATE() {
		return TNP_AG_PROFILE_ORGANIZATION_ADDRESS_STATE;
	}
	public void setTNP_AG_PROFILE_ORGANIZATION_ADDRESS_STATE(String tNP_AG_PROFILE_ORGANIZATION_ADDRESS_STATE) {
		TNP_AG_PROFILE_ORGANIZATION_ADDRESS_STATE = tNP_AG_PROFILE_ORGANIZATION_ADDRESS_STATE;
	}
	public String getTNP_AG_PROFILE_ORGANIZATION_ADDRESS_THANA() {
		return TNP_AG_PROFILE_ORGANIZATION_ADDRESS_THANA;
	}
	public void setTNP_AG_PROFILE_ORGANIZATION_ADDRESS_THANA(String tNP_AG_PROFILE_ORGANIZATION_ADDRESS_THANA) {
		TNP_AG_PROFILE_ORGANIZATION_ADDRESS_THANA = tNP_AG_PROFILE_ORGANIZATION_ADDRESS_THANA;
	}
	public String getTNP_AG_PROFILE_ORGANIZATION_ADDRESS_DISTRICT() {
		return TNP_AG_PROFILE_ORGANIZATION_ADDRESS_DISTRICT;
	}
	public void setTNP_AG_PROFILE_ORGANIZATION_ADDRESS_DISTRICT(String tNP_AG_PROFILE_ORGANIZATION_ADDRESS_DISTRICT) {
		TNP_AG_PROFILE_ORGANIZATION_ADDRESS_DISTRICT = tNP_AG_PROFILE_ORGANIZATION_ADDRESS_DISTRICT;
	}
	public String getTNP_AG_PROFILE_ORGANIZATION_ADDRESS_UNION() {
		return TNP_AG_PROFILE_ORGANIZATION_ADDRESS_UNION;
	}
	public void setTNP_AG_PROFILE_ORGANIZATION_ADDRESS_UNION(String tNP_AG_PROFILE_ORGANIZATION_ADDRESS_UNION) {
		TNP_AG_PROFILE_ORGANIZATION_ADDRESS_UNION = tNP_AG_PROFILE_ORGANIZATION_ADDRESS_UNION;
	}
	public String getTNP_AG_PROFILE_ORGANIZATION_ADDRESS_DIVISION() {
		return TNP_AG_PROFILE_ORGANIZATION_ADDRESS_DIVISION;
	}
	public void setTNP_AG_PROFILE_ORGANIZATION_ADDRESS_DIVISION(String tNP_AG_PROFILE_ORGANIZATION_ADDRESS_DIVISION) {
		TNP_AG_PROFILE_ORGANIZATION_ADDRESS_DIVISION = tNP_AG_PROFILE_ORGANIZATION_ADDRESS_DIVISION;
	}
	public String getTNP_AG_PROFILE_ORGANIZATION_ADDRESS_POSTCODE() {
		return TNP_AG_PROFILE_ORGANIZATION_ADDRESS_POSTCODE;
	}
	public void setTNP_AG_PROFILE_ORGANIZATION_ADDRESS_POSTCODE(String tNP_AG_PROFILE_ORGANIZATION_ADDRESS_POSTCODE) {
		TNP_AG_PROFILE_ORGANIZATION_ADDRESS_POSTCODE = tNP_AG_PROFILE_ORGANIZATION_ADDRESS_POSTCODE;
	}
	public String getTNP_AG_PROFILE_COMPANY_BANK_ACC_NO() {
		return TNP_AG_PROFILE_COMPANY_BANK_ACC_NO;
	}
	public void setTNP_AG_PROFILE_COMPANY_BANK_ACC_NO(String tNP_AG_PROFILE_COMPANY_BANK_ACC_NO) {
		TNP_AG_PROFILE_COMPANY_BANK_ACC_NO = tNP_AG_PROFILE_COMPANY_BANK_ACC_NO;
	}
	public String getTNP_AG_PROFILE_VAT_REG_NO() {
		return TNP_AG_PROFILE_VAT_REG_NO;
	}
	public void setTNP_AG_PROFILE_VAT_REG_NO(String tNP_AG_PROFILE_VAT_REG_NO) {
		TNP_AG_PROFILE_VAT_REG_NO = tNP_AG_PROFILE_VAT_REG_NO;
	}
	public String getTNP_AG_PROFILE_TIN_NO() {
		return TNP_AG_PROFILE_TIN_NO;
	}
	public void setTNP_AG_PROFILE_TIN_NO(String tNP_AG_PROFILE_TIN_NO) {
		TNP_AG_PROFILE_TIN_NO = tNP_AG_PROFILE_TIN_NO;
	}
	public String getTNP_AG_PROFILE_ISSUING_AUTHORITY() {
		return TNP_AG_PROFILE_ISSUING_AUTHORITY;
	}
	public void setTNP_AG_PROFILE_ISSUING_AUTHORITY(String tNP_AG_PROFILE_ISSUING_AUTHORITY) {
		TNP_AG_PROFILE_ISSUING_AUTHORITY = tNP_AG_PROFILE_ISSUING_AUTHORITY;
	}
	public String getTNP_AG_PROFILE_OTHER_CONTACT_NO() {
		return TNP_AG_PROFILE_OTHER_CONTACT_NO;
	}
	public void setTNP_AG_PROFILE_OTHER_CONTACT_NO(String tNP_AG_PROFILE_OTHER_CONTACT_NO) {
		TNP_AG_PROFILE_OTHER_CONTACT_NO = tNP_AG_PROFILE_OTHER_CONTACT_NO;
	}
	public String getTNP_AG_PROFILE_COMPANY_BANK_ACC_NAME() {
		return TNP_AG_PROFILE_COMPANY_BANK_ACC_NAME;
	}
	public void setTNP_AG_PROFILE_COMPANY_BANK_ACC_NAME(String tNP_AG_PROFILE_COMPANY_BANK_ACC_NAME) {
		TNP_AG_PROFILE_COMPANY_BANK_ACC_NAME = tNP_AG_PROFILE_COMPANY_BANK_ACC_NAME;
	}
	public String getTNP_AG_PROFILE_COMPANY_BANK_NAME() {
		return TNP_AG_PROFILE_COMPANY_BANK_NAME;
	}
	public void setTNP_AG_PROFILE_COMPANY_BANK_NAME(String tNP_AG_PROFILE_COMPANY_BANK_NAME) {
		TNP_AG_PROFILE_COMPANY_BANK_NAME = tNP_AG_PROFILE_COMPANY_BANK_NAME;
	}
	public String getTNP_AG_PROFILE_COMPANY_BANK_BRANCH() {
		return TNP_AG_PROFILE_COMPANY_BANK_BRANCH;
	}
	public void setTNP_AG_PROFILE_COMPANY_BANK_BRANCH(String tNP_AG_PROFILE_COMPANY_BANK_BRANCH) {
		TNP_AG_PROFILE_COMPANY_BANK_BRANCH = tNP_AG_PROFILE_COMPANY_BANK_BRANCH;
	}
	public String getTNP_AG_PROFILE_NAME() {
		return TNP_AG_PROFILE_NAME;
	}
	public void setTNP_AG_PROFILE_NAME(String tNP_AG_PROFILE_NAME) {
		TNP_AG_PROFILE_NAME = tNP_AG_PROFILE_NAME;
	}
	public String getTNP_AG_PROFILE_DATE_OF_BIRTH() {
		return TNP_AG_PROFILE_DATE_OF_BIRTH;
	}
	public void setTNP_AG_PROFILE_DATE_OF_BIRTH(String tNP_AG_PROFILE_DATE_OF_BIRTH) {
		TNP_AG_PROFILE_DATE_OF_BIRTH = tNP_AG_PROFILE_DATE_OF_BIRTH;
	}
	public String getTNP_AG_PROFILE_GENDER() {
		return TNP_AG_PROFILE_GENDER;
	}
	public void setTNP_AG_PROFILE_GENDER(String tNP_AG_PROFILE_GENDER) {
		TNP_AG_PROFILE_GENDER = tNP_AG_PROFILE_GENDER;
	}
	public String getTNP_AG_PROFILE_NATIONALITY() {
		return TNP_AG_PROFILE_NATIONALITY;
	}
	public void setTNP_AG_PROFILE_NATIONALITY(String tNP_AG_PROFILE_NATIONALITY) {
		TNP_AG_PROFILE_NATIONALITY = tNP_AG_PROFILE_NATIONALITY;
	}
	public String getTNP_AG_PROFILE_ID_NUMBER() {
		return TNP_AG_PROFILE_ID_NUMBER;
	}
	public void setTNP_AG_PROFILE_ID_NUMBER(String tNP_AG_PROFILE_ID_NUMBER) {
		TNP_AG_PROFILE_ID_NUMBER = tNP_AG_PROFILE_ID_NUMBER;
	}
	public String getTNP_AG_PROFILE_ID_TYPE() {
		return TNP_AG_PROFILE_ID_TYPE;
	}
	public void setTNP_AG_PROFILE_ID_TYPE(String tNP_AG_PROFILE_ID_TYPE) {
		TNP_AG_PROFILE_ID_TYPE = tNP_AG_PROFILE_ID_TYPE;
	}
	public String getTNP_AG_PROFILE_EMAIL_ID() {
		return TNP_AG_PROFILE_EMAIL_ID;
	}
	public void setTNP_AG_PROFILE_EMAIL_ID(String tNP_AG_PROFILE_EMAIL_ID) {
		TNP_AG_PROFILE_EMAIL_ID = tNP_AG_PROFILE_EMAIL_ID;
	}
	public String getTNP_AG_PROFILE_TRADE_LICENSE_NO() {
		return TNP_AG_PROFILE_TRADE_LICENSE_NO;
	}
	public void setTNP_AG_PROFILE_TRADE_LICENSE_NO(String tNP_AG_PROFILE_TRADE_LICENSE_NO) {
		TNP_AG_PROFILE_TRADE_LICENSE_NO = tNP_AG_PROFILE_TRADE_LICENSE_NO;
	}
	public String getTNP_AG_PROFILE_EMERGENCY_CONTACT_NO() {
		return TNP_AG_PROFILE_EMERGENCY_CONTACT_NO;
	}
	public void setTNP_AG_PROFILE_EMERGENCY_CONTACT_NO(String tNP_AG_PROFILE_EMERGENCY_CONTACT_NO) {
		TNP_AG_PROFILE_EMERGENCY_CONTACT_NO = tNP_AG_PROFILE_EMERGENCY_CONTACT_NO;
	}
	public String getTNP_AG_PROFILE_PROFESSION() {
		return TNP_AG_PROFILE_PROFESSION;
	}
	public void setTNP_AG_PROFILE_PROFESSION(String tNP_AG_PROFILE_PROFESSION) {
		TNP_AG_PROFILE_PROFESSION = tNP_AG_PROFILE_PROFESSION;
	}
	public String getTNP_AG_PROFILE_FATHER_NAME() {
		return TNP_AG_PROFILE_FATHER_NAME;
	}
	public void setTNP_AG_PROFILE_FATHER_NAME(String tNP_AG_PROFILE_FATHER_NAME) {
		TNP_AG_PROFILE_FATHER_NAME = tNP_AG_PROFILE_FATHER_NAME;
	}
	public String getTNP_AG_PROFILE_MOTHER_NAME() {
		return TNP_AG_PROFILE_MOTHER_NAME;
	}
	public void setTNP_AG_PROFILE_MOTHER_NAME(String tNP_AG_PROFILE_MOTHER_NAME) {
		TNP_AG_PROFILE_MOTHER_NAME = tNP_AG_PROFILE_MOTHER_NAME;
	}
	public String getTNP_AG_PROFILE_SPOUSE_NAME() {
		return TNP_AG_PROFILE_SPOUSE_NAME;
	}
	public void setTNP_AG_PROFILE_SPOUSE_NAME(String tNP_AG_PROFILE_SPOUSE_NAME) {
		TNP_AG_PROFILE_SPOUSE_NAME = tNP_AG_PROFILE_SPOUSE_NAME;
	}
	public String getTNP_AG_PROFILE_PERMANENT_ADDRESS_HOUSE_NO() {
		return TNP_AG_PROFILE_PERMANENT_ADDRESS_HOUSE_NO;
	}
	public void setTNP_AG_PROFILE_PERMANENT_ADDRESS_HOUSE_NO(String tNP_AG_PROFILE_PERMANENT_ADDRESS_HOUSE_NO) {
		TNP_AG_PROFILE_PERMANENT_ADDRESS_HOUSE_NO = tNP_AG_PROFILE_PERMANENT_ADDRESS_HOUSE_NO;
	}
	public String getTNP_AG_PROFILE_PERMANENT_ADDRESS_STREET() {
		return TNP_AG_PROFILE_PERMANENT_ADDRESS_STREET;
	}
	public void setTNP_AG_PROFILE_PERMANENT_ADDRESS_STREET(String tNP_AG_PROFILE_PERMANENT_ADDRESS_STREET) {
		TNP_AG_PROFILE_PERMANENT_ADDRESS_STREET = tNP_AG_PROFILE_PERMANENT_ADDRESS_STREET;
	}
	public String getTNP_AG_PROFILE_PERMANENT_ADDRESS_CITY() {
		return TNP_AG_PROFILE_PERMANENT_ADDRESS_CITY;
	}
	public void setTNP_AG_PROFILE_PERMANENT_ADDRESS_CITY(String tNP_AG_PROFILE_PERMANENT_ADDRESS_CITY) {
		TNP_AG_PROFILE_PERMANENT_ADDRESS_CITY = tNP_AG_PROFILE_PERMANENT_ADDRESS_CITY;
	}
	public String getTNP_AG_PROFILE_PERMANENT_ADDRESS_STATE() {
		return TNP_AG_PROFILE_PERMANENT_ADDRESS_STATE;
	}
	public void setTNP_AG_PROFILE_PERMANENT_ADDRESS_STATE(String tNP_AG_PROFILE_PERMANENT_ADDRESS_STATE) {
		TNP_AG_PROFILE_PERMANENT_ADDRESS_STATE = tNP_AG_PROFILE_PERMANENT_ADDRESS_STATE;
	}
	public String getTNP_AG_PROFILE_PERMANENT_ADDRESS_DISTRICT() {
		return TNP_AG_PROFILE_PERMANENT_ADDRESS_DISTRICT;
	}
	public void setTNP_AG_PROFILE_PERMANENT_ADDRESS_DISTRICT(String tNP_AG_PROFILE_PERMANENT_ADDRESS_DISTRICT) {
		TNP_AG_PROFILE_PERMANENT_ADDRESS_DISTRICT = tNP_AG_PROFILE_PERMANENT_ADDRESS_DISTRICT;
	}
	public String getTNP_AG_PROFILE_PERMANENT_ADDRESS_THANA() {
		return TNP_AG_PROFILE_PERMANENT_ADDRESS_THANA;
	}
	public void setTNP_AG_PROFILE_PERMANENT_ADDRESS_THANA(String tNP_AG_PROFILE_PERMANENT_ADDRESS_THANA) {
		TNP_AG_PROFILE_PERMANENT_ADDRESS_THANA = tNP_AG_PROFILE_PERMANENT_ADDRESS_THANA;
	}
	public String getTNP_AG_PROFILE_PERMANENT_ADDRESS_UNION() {
		return TNP_AG_PROFILE_PERMANENT_ADDRESS_UNION;
	}
	public void setTNP_AG_PROFILE_PERMANENT_ADDRESS_UNION(String tNP_AG_PROFILE_PERMANENT_ADDRESS_UNION) {
		TNP_AG_PROFILE_PERMANENT_ADDRESS_UNION = tNP_AG_PROFILE_PERMANENT_ADDRESS_UNION;
	}
	public String getTNP_AG_PROFILE_PERMANENT_ADDRESS_DIVISION() {
		return TNP_AG_PROFILE_PERMANENT_ADDRESS_DIVISION;
	}
	public void setTNP_AG_PROFILE_PERMANENT_ADDRESS_DIVISION(String tNP_AG_PROFILE_PERMANENT_ADDRESS_DIVISION) {
		TNP_AG_PROFILE_PERMANENT_ADDRESS_DIVISION = tNP_AG_PROFILE_PERMANENT_ADDRESS_DIVISION;
	}
	public String getTNP_AG_PROFILE_PERMANENT_ADDRESS_POSTCODE() {
		return TNP_AG_PROFILE_PERMANENT_ADDRESS_POSTCODE;
	}
	public void setTNP_AG_PROFILE_PERMANENT_ADDRESS_POSTCODE(String tNP_AG_PROFILE_PERMANENT_ADDRESS_POSTCODE) {
		TNP_AG_PROFILE_PERMANENT_ADDRESS_POSTCODE = tNP_AG_PROFILE_PERMANENT_ADDRESS_POSTCODE;
	}
	
	public String getTNP_AG_PROFILE_BANK_ACC_NO() {
		return TNP_AG_PROFILE_BANK_ACC_NO;
	}
	public void setTNP_AG_PROFILE_BANK_ACC_NO(String tNP_AG_PROFILE_BANK_ACC_NO) {
		TNP_AG_PROFILE_BANK_ACC_NO = tNP_AG_PROFILE_BANK_ACC_NO;
	}
	public String getTNP_AG_PROFILE_BANK_ACC_NAME() {
		return TNP_AG_PROFILE_BANK_ACC_NAME;
	}
	public void setTNP_AG_PROFILE_BANK_ACC_NAME(String tNP_AG_PROFILE_BANK_ACC_NAME) {
		TNP_AG_PROFILE_BANK_ACC_NAME = tNP_AG_PROFILE_BANK_ACC_NAME;
	}
	public String getTNP_AG_PROFILE_BANK_NAME() {
		return TNP_AG_PROFILE_BANK_NAME;
	}
	public void setTNP_AG_PROFILE_BANK_NAME(String tNP_AG_PROFILE_BANK_NAME) {
		TNP_AG_PROFILE_BANK_NAME = tNP_AG_PROFILE_BANK_NAME;
	}
	public String getTNP_AG_PROFILE_BANK_BRANCH() {
		return TNP_AG_PROFILE_BANK_BRANCH;
	}
	public void setTNP_AG_PROFILE_BANK_BRANCH(String tNP_AG_PROFILE_BANK_BRANCH) {
		TNP_AG_PROFILE_BANK_BRANCH = tNP_AG_PROFILE_BANK_BRANCH;
	}
	public String getTNP_AG_PROFILE_NOMINEE_NAME() {
		return TNP_AG_PROFILE_NOMINEE_NAME;
	}
	public void setTNP_AG_PROFILE_NOMINEE_NAME(String tNP_AG_PROFILE_NOMINEE_NAME) {
		TNP_AG_PROFILE_NOMINEE_NAME = tNP_AG_PROFILE_NOMINEE_NAME;
	}
	public String getTNP_AG_PROFILE_NOMINEE_RELATION() {
		return TNP_AG_PROFILE_NOMINEE_RELATION;
	}
	public void setTNP_AG_PROFILE_NOMINEE_RELATION(String tNP_AG_PROFILE_NOMINEE_RELATION) {
		TNP_AG_PROFILE_NOMINEE_RELATION = tNP_AG_PROFILE_NOMINEE_RELATION;
	}
	public String getTNP_AG_PROFILE_NOMINEE_CONTACT_NO() {
		return TNP_AG_PROFILE_NOMINEE_CONTACT_NO;
	}
	public void setTNP_AG_PROFILE_NOMINEE_CONTACT_NO(String tNP_AG_PROFILE_NOMINEE_CONTACT_NO) {
		TNP_AG_PROFILE_NOMINEE_CONTACT_NO = tNP_AG_PROFILE_NOMINEE_CONTACT_NO;
	}
	public String getTNP_AG_PROFILE_NOMINEE_FATHERS_NAME() {
		return TNP_AG_PROFILE_NOMINEE_FATHERS_NAME;
	}
	public void setTNP_AG_PROFILE_NOMINEE_FATHERS_NAME(String tNP_AG_PROFILE_NOMINEE_FATHERS_NAME) {
		TNP_AG_PROFILE_NOMINEE_FATHERS_NAME = tNP_AG_PROFILE_NOMINEE_FATHERS_NAME;
	}
	public String getTNP_AG_PROFILE_NOMINEE_MOTHERS_NAME() {
		return TNP_AG_PROFILE_NOMINEE_MOTHERS_NAME;
	}
	public void setTNP_AG_PROFILE_NOMINEE_MOTHERS_NAME(String tNP_AG_PROFILE_NOMINEE_MOTHERS_NAME) {
		TNP_AG_PROFILE_NOMINEE_MOTHERS_NAME = tNP_AG_PROFILE_NOMINEE_MOTHERS_NAME;
	}
	public String getTNP_AG_PROFILE_NOMINEE_ID_TYPE() {
		return TNP_AG_PROFILE_NOMINEE_ID_TYPE;
	}
	public void setTNP_AG_PROFILE_NOMINEE_ID_TYPE(String tNP_AG_PROFILE_NOMINEE_ID_TYPE) {
		TNP_AG_PROFILE_NOMINEE_ID_TYPE = tNP_AG_PROFILE_NOMINEE_ID_TYPE;
	}
	public String getTNP_AG_PROFILE_NOMINEE_ID_NO() {
		return TNP_AG_PROFILE_NOMINEE_ID_NO;
	}
	public void setTNP_AG_PROFILE_NOMINEE_ID_NO(String tNP_AG_PROFILE_NOMINEE_ID_NO) {
		TNP_AG_PROFILE_NOMINEE_ID_NO = tNP_AG_PROFILE_NOMINEE_ID_NO;
	}
	public String getTNP_AG_PROFILE_NOMINEE_ADDRESS_HOUSE_NO() {
		return TNP_AG_PROFILE_NOMINEE_ADDRESS_HOUSE_NO;
	}
	public void setTNP_AG_PROFILE_NOMINEE_ADDRESS_HOUSE_NO(String tNP_AG_PROFILE_NOMINEE_ADDRESS_HOUSE_NO) {
		TNP_AG_PROFILE_NOMINEE_ADDRESS_HOUSE_NO = tNP_AG_PROFILE_NOMINEE_ADDRESS_HOUSE_NO;
	}
	public String getTNP_AG_PROFILE_NOMINEE_ADDRESS_STEET() {
		return TNP_AG_PROFILE_NOMINEE_ADDRESS_STEET;
	}
	public void setTNP_AG_PROFILE_NOMINEE_ADDRESS_STEET(String tNP_AG_PROFILE_NOMINEE_ADDRESS_STEET) {
		TNP_AG_PROFILE_NOMINEE_ADDRESS_STEET = tNP_AG_PROFILE_NOMINEE_ADDRESS_STEET;
	}
	public String getTNP_AG_PROFILE_NOMINEE_ADDRESS_CITY() {
		return TNP_AG_PROFILE_NOMINEE_ADDRESS_CITY;
	}
	public void setTNP_AG_PROFILE_NOMINEE_ADDRESS_CITY(String tNP_AG_PROFILE_NOMINEE_ADDRESS_CITY) {
		TNP_AG_PROFILE_NOMINEE_ADDRESS_CITY = tNP_AG_PROFILE_NOMINEE_ADDRESS_CITY;
	}
	public String getTNP_AG_PROFILE_NOMINEE_ADDRESS_STATE() {
		return TNP_AG_PROFILE_NOMINEE_ADDRESS_STATE;
	}
	public void setTNP_AG_PROFILE_NOMINEE_ADDRESS_STATE(String tNP_AG_PROFILE_NOMINEE_ADDRESS_STATE) {
		TNP_AG_PROFILE_NOMINEE_ADDRESS_STATE = tNP_AG_PROFILE_NOMINEE_ADDRESS_STATE;
	}
	public String getTNP_AG_PROFILE_NOMINEE_DISTRICT() {
		return TNP_AG_PROFILE_NOMINEE_DISTRICT;
	}
	public void setTNP_AG_PROFILE_NOMINEE_DISTRICT(String tNP_AG_PROFILE_NOMINEE_DISTRICT) {
		TNP_AG_PROFILE_NOMINEE_DISTRICT = tNP_AG_PROFILE_NOMINEE_DISTRICT;
	}
	public String getTNP_AG_PROFILE_NOMINEE_THANA() {
		return TNP_AG_PROFILE_NOMINEE_THANA;
	}
	public void setTNP_AG_PROFILE_NOMINEE_THANA(String tNP_AG_PROFILE_NOMINEE_THANA) {
		TNP_AG_PROFILE_NOMINEE_THANA = tNP_AG_PROFILE_NOMINEE_THANA;
	}
	public String getTNP_AG_PROFILE_NOMINEE_UNION() {
		return TNP_AG_PROFILE_NOMINEE_UNION;
	}
	public void setTNP_AG_PROFILE_NOMINEE_UNION(String tNP_AG_PROFILE_NOMINEE_UNION) {
		TNP_AG_PROFILE_NOMINEE_UNION = tNP_AG_PROFILE_NOMINEE_UNION;
	}
	public String getTNP_AG_PROFILE_NOMINEE_DIVISION() {
		return TNP_AG_PROFILE_NOMINEE_DIVISION;
	}
	public void setTNP_AG_PROFILE_NOMINEE_DIVISION(String tNP_AG_PROFILE_NOMINEE_DIVISION) {
		TNP_AG_PROFILE_NOMINEE_DIVISION = tNP_AG_PROFILE_NOMINEE_DIVISION;
	}
	public String getTNP_AG_PROFILE_NOMINEE_POSTCODE() {
		return TNP_AG_PROFILE_NOMINEE_POSTCODE;
	}
	public void setTNP_AG_PROFILE_NOMINEE_POSTCODE(String tNP_AG_PROFILE_NOMINEE_POSTCODE) {
		TNP_AG_PROFILE_NOMINEE_POSTCODE = tNP_AG_PROFILE_NOMINEE_POSTCODE;
	}
	public String getTNP_AG_PROFILE_VERIFIED_USER() {
		return TNP_AG_PROFILE_VERIFIED_USER;
	}
	public void setTNP_AG_PROFILE_VERIFIED_USER(String tNP_AG_PROFILE_VERIFIED_USER) {
		TNP_AG_PROFILE_VERIFIED_USER = tNP_AG_PROFILE_VERIFIED_USER;
	}
	public String getTNP_AG_PROFILE_APPROVAL_STATUS() {
		return TNP_AG_PROFILE_APPROVAL_STATUS;
	}
	public void setTNP_AG_PROFILE_APPROVAL_STATUS(String tNP_AG_PROFILE_APPROVAL_STATUS) {
		TNP_AG_PROFILE_APPROVAL_STATUS = tNP_AG_PROFILE_APPROVAL_STATUS;
	}
	public String getTNP_AG_PROFILE_APPROVAL_COMMENTS() {
		return TNP_AG_PROFILE_APPROVAL_COMMENTS;
	}
	public void setTNP_AG_PROFILE_APPROVAL_COMMENTS(String tNP_AG_PROFILE_APPROVAL_COMMENTS) {
		TNP_AG_PROFILE_APPROVAL_COMMENTS = tNP_AG_PROFILE_APPROVAL_COMMENTS;
	}
	public String getTNP_AG_PROFILE_DSR_CODE() {
		return TNP_AG_PROFILE_DSR_CODE;
	}
	public void setTNP_AG_PROFILE_DSR_CODE(String tNP_AG_PROFILE_DSR_CODE) {
		TNP_AG_PROFILE_DSR_CODE = tNP_AG_PROFILE_DSR_CODE;
	}
	public String getTNP_AG_PROFILE_DSR_ROUTE() {
		return TNP_AG_PROFILE_DSR_ROUTE;
	}
	public void setTNP_AG_PROFILE_DSR_ROUTE(String tNP_AG_PROFILE_DSR_ROUTE) {
		TNP_AG_PROFILE_DSR_ROUTE = tNP_AG_PROFILE_DSR_ROUTE;
	}
	public String getTNP_AG_PROFILE_DSR_LIMIT() {
		return TNP_AG_PROFILE_DSR_LIMIT;
	}
	public void setTNP_AG_PROFILE_DSR_LIMIT(String tNP_AG_PROFILE_DSR_LIMIT) {
		TNP_AG_PROFILE_DSR_LIMIT = tNP_AG_PROFILE_DSR_LIMIT;
	}
	public String getTNP_AG_PROFILE_REFERANCE_NO_OTHER() {
		return TNP_AG_PROFILE_REFERANCE_NO_OTHER;
	}
	public void setTNP_AG_PROFILE_REFERANCE_NO_OTHER(String tNP_AG_PROFILE_REFERANCE_NO_OTHER) {
		TNP_AG_PROFILE_REFERANCE_NO_OTHER = tNP_AG_PROFILE_REFERANCE_NO_OTHER;
	}
	public String getTNP_AG_PROFILE_VERIFIED_IMG_NIC() {
		return TNP_AG_PROFILE_VERIFIED_IMG_NIC;
	}
	public void setTNP_AG_PROFILE_VERIFIED_IMG_NIC(String tNP_AG_PROFILE_VERIFIED_IMG_NIC) {
		TNP_AG_PROFILE_VERIFIED_IMG_NIC = tNP_AG_PROFILE_VERIFIED_IMG_NIC;
	}
	public String getTNP_AG_PROFILE_VERIFIED_IMG_PHOTO() {
		return TNP_AG_PROFILE_VERIFIED_IMG_PHOTO;
	}
	public void setTNP_AG_PROFILE_VERIFIED_IMG_PHOTO(String tNP_AG_PROFILE_VERIFIED_IMG_PHOTO) {
		TNP_AG_PROFILE_VERIFIED_IMG_PHOTO = tNP_AG_PROFILE_VERIFIED_IMG_PHOTO;
	}
	public String getTNP_AG_PROFILE_VERIFIED_IMG_KYC_FORM() {
		return TNP_AG_PROFILE_VERIFIED_IMG_KYC_FORM;
	}
	public void setTNP_AG_PROFILE_VERIFIED_IMG_KYC_FORM(String tNP_AG_PROFILE_VERIFIED_IMG_KYC_FORM) {
		TNP_AG_PROFILE_VERIFIED_IMG_KYC_FORM = tNP_AG_PROFILE_VERIFIED_IMG_KYC_FORM;
	}
	public String getTNP_AG_PROFILE_VERIFIED_IMG_UPDATED_KYC_FORM() {
		return TNP_AG_PROFILE_VERIFIED_IMG_UPDATED_KYC_FORM;
	}
	public void setTNP_AG_PROFILE_VERIFIED_IMG_UPDATED_KYC_FORM(String tNP_AG_PROFILE_VERIFIED_IMG_UPDATED_KYC_FORM) {
		TNP_AG_PROFILE_VERIFIED_IMG_UPDATED_KYC_FORM = tNP_AG_PROFILE_VERIFIED_IMG_UPDATED_KYC_FORM;
	}
	public String getTNP_AG_PROFILE_VERIFIED_TIN() {
		return TNP_AG_PROFILE_VERIFIED_TIN;
	}
	public void setTNP_AG_PROFILE_VERIFIED_TIN(String tNP_AG_PROFILE_VERIFIED_TIN) {
		TNP_AG_PROFILE_VERIFIED_TIN = tNP_AG_PROFILE_VERIFIED_TIN;
	}
	public String getTNP_AG_PROFILE_VERIFIED_TRADE_LICENSE() {
		return TNP_AG_PROFILE_VERIFIED_TRADE_LICENSE;
	}
	public void setTNP_AG_PROFILE_VERIFIED_TRADE_LICENSE(String tNP_AG_PROFILE_VERIFIED_TRADE_LICENSE) {
		TNP_AG_PROFILE_VERIFIED_TRADE_LICENSE = tNP_AG_PROFILE_VERIFIED_TRADE_LICENSE;
	}
	public String getTNP_AG_PROFILE_VERIFIED_VAT() {
		return TNP_AG_PROFILE_VERIFIED_VAT;
	}
	public void setTNP_AG_PROFILE_VERIFIED_VAT(String tNP_AG_PROFILE_VERIFIED_VAT) {
		TNP_AG_PROFILE_VERIFIED_VAT = tNP_AG_PROFILE_VERIFIED_VAT;
	}
	public String getTNP_AG_PROFILE_VERIFIED_IMG_OTHER() {
		return TNP_AG_PROFILE_VERIFIED_IMG_OTHER;
	}
	public void setTNP_AG_PROFILE_VERIFIED_IMG_OTHER(String tNP_AG_PROFILE_VERIFIED_IMG_OTHER) {
		TNP_AG_PROFILE_VERIFIED_IMG_OTHER = tNP_AG_PROFILE_VERIFIED_IMG_OTHER;
	}
	public String getTNP_AG_PROFILE_INFO1() {
		return TNP_AG_PROFILE_INFO1;
	}
	public void setTNP_AG_PROFILE_INFO1(String tNP_AG_PROFILE_INFO1) {
		TNP_AG_PROFILE_INFO1 = tNP_AG_PROFILE_INFO1;
	}
	public String getTNP_AG_PROFILE_INFO2() {
		return TNP_AG_PROFILE_INFO2;
	}
	public void setTNP_AG_PROFILE_INFO2(String tNP_AG_PROFILE_INFO2) {
		TNP_AG_PROFILE_INFO2 = tNP_AG_PROFILE_INFO2;
	}
	public String getTNP_AG_PROFILE_INFO3() {
		return TNP_AG_PROFILE_INFO3;
	}
	public void setTNP_AG_PROFILE_INFO3(String tNP_AG_PROFILE_INFO3) {
		TNP_AG_PROFILE_INFO3 = tNP_AG_PROFILE_INFO3;
	}
	public String getTNP_AG_PROFILE_INFO4() {
		return TNP_AG_PROFILE_INFO4;
	}
	public void setTNP_AG_PROFILE_INFO4(String tNP_AG_PROFILE_INFO4) {
		TNP_AG_PROFILE_INFO4 = tNP_AG_PROFILE_INFO4;
	}
	public String getTNP_AG_PROFILE_INFO5() {
		return TNP_AG_PROFILE_INFO5;
	}
	public void setTNP_AG_PROFILE_INFO5(String tNP_AG_PROFILE_INFO5) {
		TNP_AG_PROFILE_INFO5 = tNP_AG_PROFILE_INFO5;
	}
	public String getTNP_AG_PROFILE_MID() {
		return TNP_AG_PROFILE_MID;
	}
	public void setTNP_AG_PROFILE_MID(String tNP_AG_PROFILE_MID) {
		TNP_AG_PROFILE_MID = tNP_AG_PROFILE_MID;
	}
	public String getTNP_AG_PROFILE_INTRODUCER_NAME() {
		return TNP_AG_PROFILE_INTRODUCER_NAME;
	}
	public void setTNP_AG_PROFILE_INTRODUCER_NAME(String tNP_AG_PROFILE_INTRODUCER_NAME) {
		TNP_AG_PROFILE_INTRODUCER_NAME = tNP_AG_PROFILE_INTRODUCER_NAME;
	}
	public String getTNP_AG_PROFILE_INTRODUCER_MOBILE() {
		return TNP_AG_PROFILE_INTRODUCER_MOBILE;
	}
	public void setTNP_AG_PROFILE_INTRODUCER_MOBILE(String tNP_AG_PROFILE_INTRODUCER_MOBILE) {
		TNP_AG_PROFILE_INTRODUCER_MOBILE = tNP_AG_PROFILE_INTRODUCER_MOBILE;
	}
	public String getTNP_AG_PROFILE_INTRODUCER_OCCUPATION() {
		return TNP_AG_PROFILE_INTRODUCER_OCCUPATION;
	}
	public void setTNP_AG_PROFILE_INTRODUCER_OCCUPATION(String tNP_AG_PROFILE_INTRODUCER_OCCUPATION) {
		TNP_AG_PROFILE_INTRODUCER_OCCUPATION = tNP_AG_PROFILE_INTRODUCER_OCCUPATION;
	}
	public String getTNP_AG_PROFILE_INTRODUCER_HOUSE_NO() {
		return TNP_AG_PROFILE_INTRODUCER_HOUSE_NO;
	}
	public void setTNP_AG_PROFILE_INTRODUCER_HOUSE_NO(String tNP_AG_PROFILE_INTRODUCER_HOUSE_NO) {
		TNP_AG_PROFILE_INTRODUCER_HOUSE_NO = tNP_AG_PROFILE_INTRODUCER_HOUSE_NO;
	}
	public String getTNP_AG_PROFILE_INTRODUCER_STREET() {
		return TNP_AG_PROFILE_INTRODUCER_STREET;
	}
	public void setTNP_AG_PROFILE_INTRODUCER_STREET(String tNP_AG_PROFILE_INTRODUCER_STREET) {
		TNP_AG_PROFILE_INTRODUCER_STREET = tNP_AG_PROFILE_INTRODUCER_STREET;
	}
	public String getTNP_AG_PROFILE_INTRODUCER_CITY() {
		return TNP_AG_PROFILE_INTRODUCER_CITY;
	}
	public void setTNP_AG_PROFILE_INTRODUCER_CITY(String tNP_AG_PROFILE_INTRODUCER_CITY) {
		TNP_AG_PROFILE_INTRODUCER_CITY = tNP_AG_PROFILE_INTRODUCER_CITY;
	}
	public String getTNP_AG_PROFILE_INTRODUCER_STATE() {
		return TNP_AG_PROFILE_INTRODUCER_STATE;
	}
	public void setTNP_AG_PROFILE_INTRODUCER_STATE(String tNP_AG_PROFILE_INTRODUCER_STATE) {
		TNP_AG_PROFILE_INTRODUCER_STATE = tNP_AG_PROFILE_INTRODUCER_STATE;
	}
	public String getTNP_AG_PROFILE_INTRODUCER_DISTRICT() {
		return TNP_AG_PROFILE_INTRODUCER_DISTRICT;
	}
	public void setTNP_AG_PROFILE_INTRODUCER_DISTRICT(String tNP_AG_PROFILE_INTRODUCER_DISTRICT) {
		TNP_AG_PROFILE_INTRODUCER_DISTRICT = tNP_AG_PROFILE_INTRODUCER_DISTRICT;
	}
	public String getTNP_AG_PROFILE_INTRODUCER_THANA() {
		return TNP_AG_PROFILE_INTRODUCER_THANA;
	}
	public void setTNP_AG_PROFILE_INTRODUCER_THANA(String tNP_AG_PROFILE_INTRODUCER_THANA) {
		TNP_AG_PROFILE_INTRODUCER_THANA = tNP_AG_PROFILE_INTRODUCER_THANA;
	}
	public String getTNP_AG_PROFILE_INTRODUCER_UNION() {
		return TNP_AG_PROFILE_INTRODUCER_UNION;
	}
	public void setTNP_AG_PROFILE_INTRODUCER_UNION(String tNP_AG_PROFILE_INTRODUCER_UNION) {
		TNP_AG_PROFILE_INTRODUCER_UNION = tNP_AG_PROFILE_INTRODUCER_UNION;
	}
	public String getTNP_AG_PROFILE_INTRODUCER_DIVISION() {
		return TNP_AG_PROFILE_INTRODUCER_DIVISION;
	}
	public void setTNP_AG_PROFILE_INTRODUCER_DIVISION(String tNP_AG_PROFILE_INTRODUCER_DIVISION) {
		TNP_AG_PROFILE_INTRODUCER_DIVISION = tNP_AG_PROFILE_INTRODUCER_DIVISION;
	}
	public String getTNP_AG_PROFILE_INTRODUCER_POST_CODE() {
		return TNP_AG_PROFILE_INTRODUCER_POST_CODE;
	}
	public void setTNP_AG_PROFILE_INTRODUCER_POST_CODE(String tNP_AG_PROFILE_INTRODUCER_POST_CODE) {
		TNP_AG_PROFILE_INTRODUCER_POST_CODE = tNP_AG_PROFILE_INTRODUCER_POST_CODE;
	}
	
	
	public String getAgentRecordLockStatus() {
		return AgentRecordLockStatus;
	}
	public void setAgentRecordLockStatus(String agentRecordLockStatus) {
		AgentRecordLockStatus = agentRecordLockStatus;
	}
	public String getAgentRecordLockBy() {
		return AgentRecordLockBy;
	}
	public void setAgentRecordLockBy(String agentRecordLockBy) {
		AgentRecordLockBy = agentRecordLockBy;
	}
	public String getTNP_AG_PROFILE_SUBMITTED_DATE() {
		return TNP_AG_PROFILE_SUBMITTED_DATE;
	}
	public void setTNP_AG_PROFILE_SUBMITTED_DATE(String tNP_AG_PROFILE_SUBMITTED_DATE) {
		TNP_AG_PROFILE_SUBMITTED_DATE = tNP_AG_PROFILE_SUBMITTED_DATE;
	}
	public String getImage1() {
		return image1;
	}
	public void setImage1(String image1) {
		this.image1 = image1;
	}
	public String getImage2() {
		return image2;
	}
	public void setImage2(String image2) {
		this.image2 = image2;
	}
	public String getImage3() {
		return image3;
	}
	public void setImage3(String image3) {
		this.image3 = image3;
	}
	public String getImage4() {
		return image4;
	}
	public void setImage4(String image4) {
		this.image4 = image4;
	}
	public String getImage5() {
		return image5;
	}
	public void setImage5(String image5) {
		this.image5 = image5;
	}
	public String getImage6() {
		return image6;
	}
	public void setImage6(String image6) {
		this.image6 = image6;
	}
	public String getImage7() {
		return image7;
	}
	public void setImage7(String image7) {
		this.image7 = image7;
	}
	public String getImage8() {
		return image8;
	}
	public void setImage8(String image8) {
		this.image8 = image8;
	}
	public String getImage9() {
		return image9;
	}
	public void setImage9(String image9) {
		this.image9 = image9;
	}
	public String getImage10() {
		return image10;
	}
	public void setImage10(String image10) {
		this.image10 = image10;
	}
	public int getStatusCode() {
		return statusCode;
	}
	public void setStatusCode(int statusCode) {
		this.statusCode = statusCode;
	}
	public String getStatusMsg() {
		return statusMsg;
	}
	public void setStatusMsg(String statusMsg) {
		this.statusMsg = statusMsg;
	}
	public String getRequestId() {
		return requestId;
	}
	public void setRequestId(String requestId) {
		this.requestId = requestId;
	}
	public String getTNP_AG_PROFILE_IMAGES_PROFILE_UUID() {
		return TNP_AG_PROFILE_IMAGES_PROFILE_UUID;
	}
	public void setTNP_AG_PROFILE_IMAGES_PROFILE_UUID(String tNP_AG_PROFILE_IMAGES_PROFILE_UUID) {
		TNP_AG_PROFILE_IMAGES_PROFILE_UUID = tNP_AG_PROFILE_IMAGES_PROFILE_UUID;
	}
	public String getTNP_AG_PROFILE_IMAGES_PARENT_KYC_ID() {
		return TNP_AG_PROFILE_IMAGES_PARENT_KYC_ID;
	}
	public void setTNP_AG_PROFILE_IMAGES_PARENT_KYC_ID(String tNP_AG_PROFILE_IMAGES_PARENT_KYC_ID) {
		TNP_AG_PROFILE_IMAGES_PARENT_KYC_ID = tNP_AG_PROFILE_IMAGES_PARENT_KYC_ID;
	}
	public String getTNP_AG_PROFILE_IMAGES_USER_TYPE() {
		return TNP_AG_PROFILE_IMAGES_USER_TYPE;
	}
	public void setTNP_AG_PROFILE_IMAGES_USER_TYPE(String tNP_AG_PROFILE_IMAGES_USER_TYPE) {
		TNP_AG_PROFILE_IMAGES_USER_TYPE = tNP_AG_PROFILE_IMAGES_USER_TYPE;
	}
	public String getTNP_AG_PROFILE_IMAGES_KYC_NO() {
		return TNP_AG_PROFILE_IMAGES_KYC_NO;
	}
	public void setTNP_AG_PROFILE_IMAGES_KYC_NO(String tNP_AG_PROFILE_IMAGES_KYC_NO) {
		TNP_AG_PROFILE_IMAGES_KYC_NO = tNP_AG_PROFILE_IMAGES_KYC_NO;
	}
	public String getTNP_AG_PROFILE_IMAGES_NID() {
		return TNP_AG_PROFILE_IMAGES_NID;
	}
	public void setTNP_AG_PROFILE_IMAGES_NID(String tNP_AG_PROFILE_IMAGES_NID) {
		TNP_AG_PROFILE_IMAGES_NID = tNP_AG_PROFILE_IMAGES_NID;
	}
	public String getTNP_AG_PROFILE_IMAGES_PHOTO() {
		return TNP_AG_PROFILE_IMAGES_PHOTO;
	}
	public void setTNP_AG_PROFILE_IMAGES_PHOTO(String tNP_AG_PROFILE_IMAGES_PHOTO) {
		TNP_AG_PROFILE_IMAGES_PHOTO = tNP_AG_PROFILE_IMAGES_PHOTO;
	}
	public String getTNP_AG_PROFILE_IMAGES_KYC_FORM() {
		return TNP_AG_PROFILE_IMAGES_KYC_FORM;
	}
	public void setTNP_AG_PROFILE_IMAGES_KYC_FORM(String tNP_AG_PROFILE_IMAGES_KYC_FORM) {
		TNP_AG_PROFILE_IMAGES_KYC_FORM = tNP_AG_PROFILE_IMAGES_KYC_FORM;
	}
	public String getTNP_AG_PROFILE_IMAGES_TIN() {
		return TNP_AG_PROFILE_IMAGES_TIN;
	}
	public void setTNP_AG_PROFILE_IMAGES_TIN(String tNP_AG_PROFILE_IMAGES_TIN) {
		TNP_AG_PROFILE_IMAGES_TIN = tNP_AG_PROFILE_IMAGES_TIN;
	}
	public String getTNP_AG_PROFILE_IMAGES_VAT() {
		return TNP_AG_PROFILE_IMAGES_VAT;
	}
	public void setTNP_AG_PROFILE_IMAGES_VAT(String tNP_AG_PROFILE_IMAGES_VAT) {
		TNP_AG_PROFILE_IMAGES_VAT = tNP_AG_PROFILE_IMAGES_VAT;
	}
	public String getTNP_AG_PROFILE_IMAGES_OWNERSHIP_FORM() {
		return TNP_AG_PROFILE_IMAGES_OWNERSHIP_FORM;
	}
	public void setTNP_AG_PROFILE_IMAGES_OWNERSHIP_FORM(String tNP_AG_PROFILE_IMAGES_OWNERSHIP_FORM) {
		TNP_AG_PROFILE_IMAGES_OWNERSHIP_FORM = tNP_AG_PROFILE_IMAGES_OWNERSHIP_FORM;
	}
	public String getTNP_AG_PROFILE_IMAGES_TRADE_LICENSE() {
		return TNP_AG_PROFILE_IMAGES_TRADE_LICENSE;
	}
	public void setTNP_AG_PROFILE_IMAGES_TRADE_LICENSE(String tNP_AG_PROFILE_IMAGES_TRADE_LICENSE) {
		TNP_AG_PROFILE_IMAGES_TRADE_LICENSE = tNP_AG_PROFILE_IMAGES_TRADE_LICENSE;
	}
	public String getTNP_AG_PROFILE_IMAGES_OTHER() {
		return TNP_AG_PROFILE_IMAGES_OTHER;
	}
	public void setTNP_AG_PROFILE_IMAGES_OTHER(String tNP_AG_PROFILE_IMAGES_OTHER) {
		TNP_AG_PROFILE_IMAGES_OTHER = tNP_AG_PROFILE_IMAGES_OTHER;
	}
	public String getTNP_AG_PROFILE_IMAGES_NOMINEE_PHOTO() {
		return TNP_AG_PROFILE_IMAGES_NOMINEE_PHOTO;
	}
	public void setTNP_AG_PROFILE_IMAGES_NOMINEE_PHOTO(String tNP_AG_PROFILE_IMAGES_NOMINEE_PHOTO) {
		TNP_AG_PROFILE_IMAGES_NOMINEE_PHOTO = tNP_AG_PROFILE_IMAGES_NOMINEE_PHOTO;
	}
	public String getTNP_AG_PROFILE_IMAGES_NOMINEE_NID() {
		return TNP_AG_PROFILE_IMAGES_NOMINEE_NID;
	}
	public void setTNP_AG_PROFILE_IMAGES_NOMINEE_NID(String tNP_AG_PROFILE_IMAGES_NOMINEE_NID) {
		TNP_AG_PROFILE_IMAGES_NOMINEE_NID = tNP_AG_PROFILE_IMAGES_NOMINEE_NID;
	}
	public String getTNP_AG_PROFILE_IMAGES_RESOLUTION() {
		return TNP_AG_PROFILE_IMAGES_RESOLUTION;
	}
	public void setTNP_AG_PROFILE_IMAGES_RESOLUTION(String tNP_AG_PROFILE_IMAGES_RESOLUTION) {
		TNP_AG_PROFILE_IMAGES_RESOLUTION = tNP_AG_PROFILE_IMAGES_RESOLUTION;
	}
	public String getTNP_AG_PROFILE_IMAGES_NGO_CERTIFICATE() {
		return TNP_AG_PROFILE_IMAGES_NGO_CERTIFICATE;
	}
	public void setTNP_AG_PROFILE_IMAGES_NGO_CERTIFICATE(String tNP_AG_PROFILE_IMAGES_NGO_CERTIFICATE) {
		TNP_AG_PROFILE_IMAGES_NGO_CERTIFICATE = tNP_AG_PROFILE_IMAGES_NGO_CERTIFICATE;
	}
	public String getTNP_AG_PROFILE_IMAGES_MRA_CERTIFICATE() {
		return TNP_AG_PROFILE_IMAGES_MRA_CERTIFICATE;
	}
	public void setTNP_AG_PROFILE_IMAGES_MRA_CERTIFICATE(String tNP_AG_PROFILE_IMAGES_MRA_CERTIFICATE) {
		TNP_AG_PROFILE_IMAGES_MRA_CERTIFICATE = tNP_AG_PROFILE_IMAGES_MRA_CERTIFICATE;
	}
	public String getTNP_AG_PROFILE_IMAGES_CITIZEN_CERTIFICATE() {
		return TNP_AG_PROFILE_IMAGES_CITIZEN_CERTIFICATE;
	}
	public void setTNP_AG_PROFILE_IMAGES_CITIZEN_CERTIFICATE(String tNP_AG_PROFILE_IMAGES_CITIZEN_CERTIFICATE) {
		TNP_AG_PROFILE_IMAGES_CITIZEN_CERTIFICATE = tNP_AG_PROFILE_IMAGES_CITIZEN_CERTIFICATE;
	}
	public String getTNP_AG_PROFILE_IMAGES_NFO1() {
		return TNP_AG_PROFILE_IMAGES_NFO1;
	}
	public void setTNP_AG_PROFILE_IMAGES_NFO1(String tNP_AG_PROFILE_IMAGES_NFO1) {
		TNP_AG_PROFILE_IMAGES_NFO1 = tNP_AG_PROFILE_IMAGES_NFO1;
	}
	public String getTNP_AG_PROFILE_IMAGES_NFO2() {
		return TNP_AG_PROFILE_IMAGES_NFO2;
	}
	public void setTNP_AG_PROFILE_IMAGES_NFO2(String tNP_AG_PROFILE_IMAGES_NFO2) {
		TNP_AG_PROFILE_IMAGES_NFO2 = tNP_AG_PROFILE_IMAGES_NFO2;
	}
	public String getTNP_AG_PROFILE_IMAGES_NFO3() {
		return TNP_AG_PROFILE_IMAGES_NFO3;
	}
	public void setTNP_AG_PROFILE_IMAGES_NFO3(String tNP_AG_PROFILE_IMAGES_NFO3) {
		TNP_AG_PROFILE_IMAGES_NFO3 = tNP_AG_PROFILE_IMAGES_NFO3;
	}
	public String getTNP_AG_PROFILE_IMAGES_NFO4() {
		return TNP_AG_PROFILE_IMAGES_NFO4;
	}
	public void setTNP_AG_PROFILE_IMAGES_NFO4(String tNP_AG_PROFILE_IMAGES_NFO4) {
		TNP_AG_PROFILE_IMAGES_NFO4 = tNP_AG_PROFILE_IMAGES_NFO4;
	}
	public String getTNP_AG_PROFILE_IMAGES_NFO5() {
		return TNP_AG_PROFILE_IMAGES_NFO5;
	}
	public void setTNP_AG_PROFILE_IMAGES_NFO5(String tNP_AG_PROFILE_IMAGES_NFO5) {
		TNP_AG_PROFILE_IMAGES_NFO5 = tNP_AG_PROFILE_IMAGES_NFO5;
	}
	public String getImage_nid() {
		return image_nid;
	}
	public void setImage_nid(String image_nid) {
		this.image_nid = image_nid;
	}
	public String getImage_photo() {
		return image_photo;
	}
	public void setImage_photo(String image_photo) {
		this.image_photo = image_photo;
	}
	public String getImage_kyc() {
		return image_kyc;
	}
	public void setImage_kyc(String image_kyc) {
		this.image_kyc = image_kyc;
	}
	public String getImage_tin() {
		return image_tin;
	}
	public void setImage_tin(String image_tin) {
		this.image_tin = image_tin;
	}
	public String getImage_vat() {
		return image_vat;
	}
	public void setImage_vat(String image_vat) {
		this.image_vat = image_vat;
	}
	public String getImage_ownership() {
		return image_ownership;
	}
	public void setImage_ownership(String image_ownership) {
		this.image_ownership = image_ownership;
	}
	public String getImage_trade() {
		return image_trade;
	}
	public void setImage_trade(String image_trade) {
		this.image_trade = image_trade;
	}
	public String getImage_nominee() {
		return image_nominee;
	}
	public void setImage_nominee(String image_nominee) {
		this.image_nominee = image_nominee;
	}
	public String getImage_nomineeId() {
		return image_nomineeId;
	}
	public void setImage_nomineeId(String image_nomineeId) {
		this.image_nomineeId = image_nomineeId;
	}
	public String getImage_other() {
		return image_other;
	}
	public void setImage_other(String image_other) {
		this.image_other = image_other;
	}
	public String getLock_status() {
		return lock_status;
	}
	public void setLock_status(String lock_status) {
		this.lock_status = lock_status;
	}
	public String getLock_by() {
		return lock_by;
	}
	public void setLock_by(String lock_by) {
		this.lock_by = lock_by;
	}
	public String getLock_time() {
		return lock_time;
	}
	public void setLock_time(String lock_time) {
		this.lock_time = lock_time;
	}
	public String getTNP_AG_PROFILE_IMAGES_STATUS() {
		return TNP_AG_PROFILE_IMAGES_STATUS;
	}
	public void setTNP_AG_PROFILE_IMAGES_STATUS(String tNP_AG_PROFILE_IMAGES_STATUS) {
		TNP_AG_PROFILE_IMAGES_STATUS = tNP_AG_PROFILE_IMAGES_STATUS;
	}
	public String getTNP_AG_PROFILE_IMAGES_BANK_STATUS() {
		return TNP_AG_PROFILE_IMAGES_BANK_STATUS;
	}
	public void setTNP_AG_PROFILE_IMAGES_BANK_STATUS(String tNP_AG_PROFILE_IMAGES_BANK_STATUS) {
		TNP_AG_PROFILE_IMAGES_BANK_STATUS = tNP_AG_PROFILE_IMAGES_BANK_STATUS;
	}
	public String getTNP_AG_PROFILE_IMAGES_BANK_MODIFY_DATE() {
		return TNP_AG_PROFILE_IMAGES_BANK_MODIFY_DATE;
	}
	public void setTNP_AG_PROFILE_IMAGES_BANK_MODIFY_DATE(String tNP_AG_PROFILE_IMAGES_BANK_MODIFY_DATE) {
		TNP_AG_PROFILE_IMAGES_BANK_MODIFY_DATE = tNP_AG_PROFILE_IMAGES_BANK_MODIFY_DATE;
	}
	public String getTNP_AG_PROFILE_IMAGES_BANK_REJECT_REASON() {
		return TNP_AG_PROFILE_IMAGES_BANK_REJECT_REASON;
	}
	public void setTNP_AG_PROFILE_IMAGES_BANK_REJECT_REASON(String tNP_AG_PROFILE_IMAGES_BANK_REJECT_REASON) {
		TNP_AG_PROFILE_IMAGES_BANK_REJECT_REASON = tNP_AG_PROFILE_IMAGES_BANK_REJECT_REASON;
	}
	public String getTNP_AG_PROFILE_IMAGES_LOCK_STATUS() {
		return TNP_AG_PROFILE_IMAGES_LOCK_STATUS;
	}
	public void setTNP_AG_PROFILE_IMAGES_LOCK_STATUS(String tNP_AG_PROFILE_IMAGES_LOCK_STATUS) {
		TNP_AG_PROFILE_IMAGES_LOCK_STATUS = tNP_AG_PROFILE_IMAGES_LOCK_STATUS;
	}
	public String getImage_nid_path() {
		return image_nid_path;
	}
	public void setImage_nid_path(String image_nid_path) {
		this.image_nid_path = image_nid_path;
	}
	public String getImage_photo_path() {
		return image_photo_path;
	}
	public void setImage_photo_path(String image_photo_path) {
		this.image_photo_path = image_photo_path;
	}
	public String getImage_kyc_path() {
		return image_kyc_path;
	}
	public void setImage_kyc_path(String image_kyc_path) {
		this.image_kyc_path = image_kyc_path;
	}
	public String getImage_tin_path() {
		return image_tin_path;
	}
	public void setImage_tin_path(String image_tin_path) {
		this.image_tin_path = image_tin_path;
	}
	public String getImage_vat_path() {
		return image_vat_path;
	}
	public void setImage_vat_path(String image_vat_path) {
		this.image_vat_path = image_vat_path;
	}
	public String getImage_ownership_path() {
		return image_ownership_path;
	}
	public void setImage_ownership_path(String image_ownership_path) {
		this.image_ownership_path = image_ownership_path;
	}
	public String getImage_trade_path() {
		return image_trade_path;
	}
	public void setImage_trade_path(String image_trade_path) {
		this.image_trade_path = image_trade_path;
	}
	public String getImage_other_path() {
		return image_other_path;
	}
	public void setImage_other_path(String image_other_path) {
		this.image_other_path = image_other_path;
	}
	
	
	
	

}
