package com.evidu.bank.model;

public class AgentImageVO {
	
	private int TNP_AG_PROFILE_IMAGES_AUTOID;
	private String TNP_AG_PROFILE_IMAGES_PROFILE_UUID;
	private String TNP_AG_PROFILE_IMAGES_PARENT_KYC_ID;
	private String TNP_AG_PROFILE_IMAGES_USER_TYPE;
	private String TNP_AG_PROFILE_IMAGES_KYC_NO;
	
	private byte[] TNP_AG_PROFILE_IMAGES_NID;
	private byte[] TNP_AG_PROFILE_IMAGES_PHOTO;
	private byte[] TNP_AG_PROFILE_IMAGES_KYC_FORM;
	private byte[] TNP_AG_PROFILE_IMAGES_TIN;
	private byte[] TNP_AG_PROFILE_IMAGES_VAT;
	private byte[] TNP_AG_PROFILE_IMAGES_OWNERSHIP_FORM;
	private byte[] TNP_AG_PROFILE_IMAGES_TRADE_LICENSE;
	private byte[] TNP_AG_PROFILE_IMAGES_OTHER;
	private byte[] TNP_AG_PROFILE_IMAGES_NOMINEE_PHOTO;
	private byte[] TNP_AG_PROFILE_IMAGES_NOMINEE_NID;
	private byte[] TNP_AG_PROFILE_IMAGES_RESOLUTION;
	private byte[] TNP_AG_PROFILE_IMAGES_NGO_CERTIFICATE;
	private byte[] TNP_AG_PROFILE_IMAGES_MRA_CERTIFICATE;
	private byte[] TNP_AG_PROFILE_IMAGES_CITIZEN_CERTIFICATE;
	
	private String TNP_AG_PROFILE_IMAGES_NFO1;
	private String TNP_AG_PROFILE_IMAGES_NFO2;
	private String TNP_AG_PROFILE_IMAGES_NFO3;
	private String TNP_AG_PROFILE_IMAGES_NFO4;
	private String TNP_AG_PROFILE_IMAGES_NFO5;
	
	public int getTNP_AG_PROFILE_IMAGES_AUTOID() {
		return TNP_AG_PROFILE_IMAGES_AUTOID;
	}
	public void setTNP_AG_PROFILE_IMAGES_AUTOID(int tNP_AG_PROFILE_IMAGES_AUTOID) {
		TNP_AG_PROFILE_IMAGES_AUTOID = tNP_AG_PROFILE_IMAGES_AUTOID;
	}
	public String getTNP_AG_PROFILE_IMAGES_PROFILE_UUID() {
		return TNP_AG_PROFILE_IMAGES_PROFILE_UUID;
	}
	public void setTNP_AG_PROFILE_IMAGES_PROFILE_UUID(
			String tNP_AG_PROFILE_IMAGES_PROFILE_UUID) {
		TNP_AG_PROFILE_IMAGES_PROFILE_UUID = tNP_AG_PROFILE_IMAGES_PROFILE_UUID;
	}
	public String getTNP_AG_PROFILE_IMAGES_PARENT_KYC_ID() {
		return TNP_AG_PROFILE_IMAGES_PARENT_KYC_ID;
	}
	public void setTNP_AG_PROFILE_IMAGES_PARENT_KYC_ID(
			String tNP_AG_PROFILE_IMAGES_PARENT_KYC_ID) {
		TNP_AG_PROFILE_IMAGES_PARENT_KYC_ID = tNP_AG_PROFILE_IMAGES_PARENT_KYC_ID;
	}
	public String getTNP_AG_PROFILE_IMAGES_USER_TYPE() {
		return TNP_AG_PROFILE_IMAGES_USER_TYPE;
	}
	public void setTNP_AG_PROFILE_IMAGES_USER_TYPE(
			String tNP_AG_PROFILE_IMAGES_USER_TYPE) {
		TNP_AG_PROFILE_IMAGES_USER_TYPE = tNP_AG_PROFILE_IMAGES_USER_TYPE;
	}
	public String getTNP_AG_PROFILE_IMAGES_KYC_NO() {
		return TNP_AG_PROFILE_IMAGES_KYC_NO;
	}
	public void setTNP_AG_PROFILE_IMAGES_KYC_NO(String tNP_AG_PROFILE_IMAGES_KYC_NO) {
		TNP_AG_PROFILE_IMAGES_KYC_NO = tNP_AG_PROFILE_IMAGES_KYC_NO;
	}
	public byte[] getTNP_AG_PROFILE_IMAGES_NID() {
		return TNP_AG_PROFILE_IMAGES_NID;
	}
	public void setTNP_AG_PROFILE_IMAGES_NID(byte[] tNP_AG_PROFILE_IMAGES_NID) {
		TNP_AG_PROFILE_IMAGES_NID = tNP_AG_PROFILE_IMAGES_NID;
	}
	public byte[] getTNP_AG_PROFILE_IMAGES_PHOTO() {
		return TNP_AG_PROFILE_IMAGES_PHOTO;
	}
	public void setTNP_AG_PROFILE_IMAGES_PHOTO(byte[] tNP_AG_PROFILE_IMAGES_PHOTO) {
		TNP_AG_PROFILE_IMAGES_PHOTO = tNP_AG_PROFILE_IMAGES_PHOTO;
	}
	public byte[] getTNP_AG_PROFILE_IMAGES_KYC_FORM() {
		return TNP_AG_PROFILE_IMAGES_KYC_FORM;
	}
	public void setTNP_AG_PROFILE_IMAGES_KYC_FORM(
			byte[] tNP_AG_PROFILE_IMAGES_KYC_FORM) {
		TNP_AG_PROFILE_IMAGES_KYC_FORM = tNP_AG_PROFILE_IMAGES_KYC_FORM;
	}
	public byte[] getTNP_AG_PROFILE_IMAGES_TIN() {
		return TNP_AG_PROFILE_IMAGES_TIN;
	}
	public void setTNP_AG_PROFILE_IMAGES_TIN(byte[] tNP_AG_PROFILE_IMAGES_TIN) {
		TNP_AG_PROFILE_IMAGES_TIN = tNP_AG_PROFILE_IMAGES_TIN;
	}
	public byte[] getTNP_AG_PROFILE_IMAGES_VAT() {
		return TNP_AG_PROFILE_IMAGES_VAT;
	}
	public void setTNP_AG_PROFILE_IMAGES_VAT(byte[] tNP_AG_PROFILE_IMAGES_VAT) {
		TNP_AG_PROFILE_IMAGES_VAT = tNP_AG_PROFILE_IMAGES_VAT;
	}
	public byte[] getTNP_AG_PROFILE_IMAGES_OWNERSHIP_FORM() {
		return TNP_AG_PROFILE_IMAGES_OWNERSHIP_FORM;
	}
	public void setTNP_AG_PROFILE_IMAGES_OWNERSHIP_FORM(
			byte[] tNP_AG_PROFILE_IMAGES_OWNERSHIP_FORM) {
		TNP_AG_PROFILE_IMAGES_OWNERSHIP_FORM = tNP_AG_PROFILE_IMAGES_OWNERSHIP_FORM;
	}
	public byte[] getTNP_AG_PROFILE_IMAGES_TRADE_LICENSE() {
		return TNP_AG_PROFILE_IMAGES_TRADE_LICENSE;
	}
	public void setTNP_AG_PROFILE_IMAGES_TRADE_LICENSE(
			byte[] tNP_AG_PROFILE_IMAGES_TRADE_LICENSE) {
		TNP_AG_PROFILE_IMAGES_TRADE_LICENSE = tNP_AG_PROFILE_IMAGES_TRADE_LICENSE;
	}
	public byte[] getTNP_AG_PROFILE_IMAGES_OTHER() {
		return TNP_AG_PROFILE_IMAGES_OTHER;
	}
	public void setTNP_AG_PROFILE_IMAGES_OTHER(byte[] tNP_AG_PROFILE_IMAGES_OTHER) {
		TNP_AG_PROFILE_IMAGES_OTHER = tNP_AG_PROFILE_IMAGES_OTHER;
	}
	public byte[] getTNP_AG_PROFILE_IMAGES_NOMINEE_PHOTO() {
		return TNP_AG_PROFILE_IMAGES_NOMINEE_PHOTO;
	}
	public void setTNP_AG_PROFILE_IMAGES_NOMINEE_PHOTO(
			byte[] tNP_AG_PROFILE_IMAGES_NOMINEE_PHOTO) {
		TNP_AG_PROFILE_IMAGES_NOMINEE_PHOTO = tNP_AG_PROFILE_IMAGES_NOMINEE_PHOTO;
	}
	public byte[] getTNP_AG_PROFILE_IMAGES_NOMINEE_NID() {
		return TNP_AG_PROFILE_IMAGES_NOMINEE_NID;
	}
	public void setTNP_AG_PROFILE_IMAGES_NOMINEE_NID(
			byte[] tNP_AG_PROFILE_IMAGES_NOMINEE_NID) {
		TNP_AG_PROFILE_IMAGES_NOMINEE_NID = tNP_AG_PROFILE_IMAGES_NOMINEE_NID;
	}
	public byte[] getTNP_AG_PROFILE_IMAGES_RESOLUTION() {
		return TNP_AG_PROFILE_IMAGES_RESOLUTION;
	}
	public void setTNP_AG_PROFILE_IMAGES_RESOLUTION(
			byte[] tNP_AG_PROFILE_IMAGES_RESOLUTION) {
		TNP_AG_PROFILE_IMAGES_RESOLUTION = tNP_AG_PROFILE_IMAGES_RESOLUTION;
	}
	public byte[] getTNP_AG_PROFILE_IMAGES_NGO_CERTIFICATE() {
		return TNP_AG_PROFILE_IMAGES_NGO_CERTIFICATE;
	}
	public void setTNP_AG_PROFILE_IMAGES_NGO_CERTIFICATE(
			byte[] tNP_AG_PROFILE_IMAGES_NGO_CERTIFICATE) {
		TNP_AG_PROFILE_IMAGES_NGO_CERTIFICATE = tNP_AG_PROFILE_IMAGES_NGO_CERTIFICATE;
	}
	public byte[] getTNP_AG_PROFILE_IMAGES_MRA_CERTIFICATE() {
		return TNP_AG_PROFILE_IMAGES_MRA_CERTIFICATE;
	}
	public void setTNP_AG_PROFILE_IMAGES_MRA_CERTIFICATE(
			byte[] tNP_AG_PROFILE_IMAGES_MRA_CERTIFICATE) {
		TNP_AG_PROFILE_IMAGES_MRA_CERTIFICATE = tNP_AG_PROFILE_IMAGES_MRA_CERTIFICATE;
	}
	public byte[] getTNP_AG_PROFILE_IMAGES_CITIZEN_CERTIFICATE() {
		return TNP_AG_PROFILE_IMAGES_CITIZEN_CERTIFICATE;
	}
	public void setTNP_AG_PROFILE_IMAGES_CITIZEN_CERTIFICATE(
			byte[] tNP_AG_PROFILE_IMAGES_CITIZEN_CERTIFICATE) {
		TNP_AG_PROFILE_IMAGES_CITIZEN_CERTIFICATE = tNP_AG_PROFILE_IMAGES_CITIZEN_CERTIFICATE;
	}
	public String getTNP_AG_PROFILE_IMAGES_NFO1() {
		return TNP_AG_PROFILE_IMAGES_NFO1;
	}
	public void setTNP_AG_PROFILE_IMAGES_NFO1(String tNP_AG_PROFILE_IMAGES_NFO1) {
		TNP_AG_PROFILE_IMAGES_NFO1 = tNP_AG_PROFILE_IMAGES_NFO1;
	}
	public String getTNP_AG_PROFILE_IMAGES_NFO2() {
		return TNP_AG_PROFILE_IMAGES_NFO2;
	}
	public void setTNP_AG_PROFILE_IMAGES_NFO2(String tNP_AG_PROFILE_IMAGES_NFO2) {
		TNP_AG_PROFILE_IMAGES_NFO2 = tNP_AG_PROFILE_IMAGES_NFO2;
	}
	public String getTNP_AG_PROFILE_IMAGES_NFO3() {
		return TNP_AG_PROFILE_IMAGES_NFO3;
	}
	public void setTNP_AG_PROFILE_IMAGES_NFO3(String tNP_AG_PROFILE_IMAGES_NFO3) {
		TNP_AG_PROFILE_IMAGES_NFO3 = tNP_AG_PROFILE_IMAGES_NFO3;
	}
	public String getTNP_AG_PROFILE_IMAGES_NFO4() {
		return TNP_AG_PROFILE_IMAGES_NFO4;
	}
	public void setTNP_AG_PROFILE_IMAGES_NFO4(String tNP_AG_PROFILE_IMAGES_NFO4) {
		TNP_AG_PROFILE_IMAGES_NFO4 = tNP_AG_PROFILE_IMAGES_NFO4;
	}
	public String getTNP_AG_PROFILE_IMAGES_NFO5() {
		return TNP_AG_PROFILE_IMAGES_NFO5;
	}
	public void setTNP_AG_PROFILE_IMAGES_NFO5(String tNP_AG_PROFILE_IMAGES_NFO5) {
		TNP_AG_PROFILE_IMAGES_NFO5 = tNP_AG_PROFILE_IMAGES_NFO5;
	}
			

}
