package com.evidu.bank.model;

import java.util.Date;

public class CustomerImagesVO {
	
	private int TNP_CX_PROFILE_IMAGES_AUTOID;
	private String TNP_CX_PROFILE_IMAGES_PROFILE_UUID;
	private String TNP_CX_PROFILE_IMAGES_CREATEBY;
	private Date TNP_CX_PROFILE_IMAGES_CREATE_DATE;
	private String TNP_CX_PROFILE_IMAGES_MOBILE_NUMBER;
	private String TNP_CX_PROFILE_IMAGES_REF_NO;
	private String TNP_CX_PROFILE_IMAGES_KYC_NO;
		
	private  byte[] TNP_CX_PROFILE_IMAGES_NID;
	private  byte[] TNP_CX_PROFILE_IMAGES_PHOTO;
	private  byte[] TNP_CX_PROFILE_IMAGES_KYC_FORM;
	private  byte[] TNP_CX_PROFILE_IMAGES_TIN_FORM;
	private  byte[] TNP_CX_PROFILE_IMAGES_CITIZEN_CERTIFICATE_FORM;
	private  byte[] TNP_CX_PROFILE_IMAGES_OTHER;
	
	private String TNP_CX_PROFILE_IMAGES_NFO1;
	private String TNP_CX_PROFILE_IMAGES_NFO2;
	private String TNP_CX_PROFILE_IMAGES_NFO3;
	private String TNP_CX_PROFILE_IMAGES_NFO4;
	private String TNP_CX_PROFILE_IMAGES_NFO5;
	
	public int getTNP_CX_PROFILE_IMAGES_AUTOID() {
		return TNP_CX_PROFILE_IMAGES_AUTOID;
	}
	public void setTNP_CX_PROFILE_IMAGES_AUTOID(int tNP_CX_PROFILE_IMAGES_AUTOID) {
		TNP_CX_PROFILE_IMAGES_AUTOID = tNP_CX_PROFILE_IMAGES_AUTOID;
	}
	public String getTNP_CX_PROFILE_IMAGES_PROFILE_UUID() {
		return TNP_CX_PROFILE_IMAGES_PROFILE_UUID;
	}
	public void setTNP_CX_PROFILE_IMAGES_PROFILE_UUID(
			String tNP_CX_PROFILE_IMAGES_PROFILE_UUID) {
		TNP_CX_PROFILE_IMAGES_PROFILE_UUID = tNP_CX_PROFILE_IMAGES_PROFILE_UUID;
	}
	public String getTNP_CX_PROFILE_IMAGES_CREATEBY() {
		return TNP_CX_PROFILE_IMAGES_CREATEBY;
	}
	public void setTNP_CX_PROFILE_IMAGES_CREATEBY(
			String tNP_CX_PROFILE_IMAGES_CREATEBY) {
		TNP_CX_PROFILE_IMAGES_CREATEBY = tNP_CX_PROFILE_IMAGES_CREATEBY;
	}
	public Date getTNP_CX_PROFILE_IMAGES_CREATE_DATE() {
		return TNP_CX_PROFILE_IMAGES_CREATE_DATE;
	}
	public void setTNP_CX_PROFILE_IMAGES_CREATE_DATE(
			Date tNP_CX_PROFILE_IMAGES_CREATE_DATE) {
		TNP_CX_PROFILE_IMAGES_CREATE_DATE = tNP_CX_PROFILE_IMAGES_CREATE_DATE;
	}
	public String getTNP_CX_PROFILE_IMAGES_MOBILE_NUMBER() {
		return TNP_CX_PROFILE_IMAGES_MOBILE_NUMBER;
	}
	public void setTNP_CX_PROFILE_IMAGES_MOBILE_NUMBER(
			String tNP_CX_PROFILE_IMAGES_MOBILE_NUMBER) {
		TNP_CX_PROFILE_IMAGES_MOBILE_NUMBER = tNP_CX_PROFILE_IMAGES_MOBILE_NUMBER;
	}
	public String getTNP_CX_PROFILE_IMAGES_REF_NO() {
		return TNP_CX_PROFILE_IMAGES_REF_NO;
	}
	public void setTNP_CX_PROFILE_IMAGES_REF_NO(String tNP_CX_PROFILE_IMAGES_REF_NO) {
		TNP_CX_PROFILE_IMAGES_REF_NO = tNP_CX_PROFILE_IMAGES_REF_NO;
	}
	public String getTNP_CX_PROFILE_IMAGES_KYC_NO() {
		return TNP_CX_PROFILE_IMAGES_KYC_NO;
	}
	public void setTNP_CX_PROFILE_IMAGES_KYC_NO(String tNP_CX_PROFILE_IMAGES_KYC_NO) {
		TNP_CX_PROFILE_IMAGES_KYC_NO = tNP_CX_PROFILE_IMAGES_KYC_NO;
	}
	public byte[] getTNP_CX_PROFILE_IMAGES_NID() {
		return TNP_CX_PROFILE_IMAGES_NID;
	}
	public void setTNP_CX_PROFILE_IMAGES_NID(byte[] tNP_CX_PROFILE_IMAGES_NID) {
		TNP_CX_PROFILE_IMAGES_NID = tNP_CX_PROFILE_IMAGES_NID;
	}
	public byte[] getTNP_CX_PROFILE_IMAGES_PHOTO() {
		return TNP_CX_PROFILE_IMAGES_PHOTO;
	}
	public void setTNP_CX_PROFILE_IMAGES_PHOTO(byte[] tNP_CX_PROFILE_IMAGES_PHOTO) {
		TNP_CX_PROFILE_IMAGES_PHOTO = tNP_CX_PROFILE_IMAGES_PHOTO;
	}
	public byte[] getTNP_CX_PROFILE_IMAGES_KYC_FORM() {
		return TNP_CX_PROFILE_IMAGES_KYC_FORM;
	}
	public void setTNP_CX_PROFILE_IMAGES_KYC_FORM(
			byte[] tNP_CX_PROFILE_IMAGES_KYC_FORM) {
		TNP_CX_PROFILE_IMAGES_KYC_FORM = tNP_CX_PROFILE_IMAGES_KYC_FORM;
	}
	public byte[] getTNP_CX_PROFILE_IMAGES_TIN_FORM() {
		return TNP_CX_PROFILE_IMAGES_TIN_FORM;
	}
	public void setTNP_CX_PROFILE_IMAGES_TIN_FORM(
			byte[] tNP_CX_PROFILE_IMAGES_TIN_FORM) {
		TNP_CX_PROFILE_IMAGES_TIN_FORM = tNP_CX_PROFILE_IMAGES_TIN_FORM;
	}
	public byte[] getTNP_CX_PROFILE_IMAGES_CITIZEN_CERTIFICATE_FORM() {
		return TNP_CX_PROFILE_IMAGES_CITIZEN_CERTIFICATE_FORM;
	}
	public void setTNP_CX_PROFILE_IMAGES_CITIZEN_CERTIFICATE_FORM(
			byte[] tNP_CX_PROFILE_IMAGES_CITIZEN_CERTIFICATE_FORM) {
		TNP_CX_PROFILE_IMAGES_CITIZEN_CERTIFICATE_FORM = tNP_CX_PROFILE_IMAGES_CITIZEN_CERTIFICATE_FORM;
	}
	public byte[] getTNP_CX_PROFILE_IMAGES_OTHER() {
		return TNP_CX_PROFILE_IMAGES_OTHER;
	}
	public void setTNP_CX_PROFILE_IMAGES_OTHER(byte[] tNP_CX_PROFILE_IMAGES_OTHER) {
		TNP_CX_PROFILE_IMAGES_OTHER = tNP_CX_PROFILE_IMAGES_OTHER;
	}
	public String getTNP_CX_PROFILE_IMAGES_NFO1() {
		return TNP_CX_PROFILE_IMAGES_NFO1;
	}
	public void setTNP_CX_PROFILE_IMAGES_NFO1(String tNP_CX_PROFILE_IMAGES_NFO1) {
		TNP_CX_PROFILE_IMAGES_NFO1 = tNP_CX_PROFILE_IMAGES_NFO1;
	}
	public String getTNP_CX_PROFILE_IMAGES_NFO2() {
		return TNP_CX_PROFILE_IMAGES_NFO2;
	}
	public void setTNP_CX_PROFILE_IMAGES_NFO2(String tNP_CX_PROFILE_IMAGES_NFO2) {
		TNP_CX_PROFILE_IMAGES_NFO2 = tNP_CX_PROFILE_IMAGES_NFO2;
	}
	public String getTNP_CX_PROFILE_IMAGES_NFO3() {
		return TNP_CX_PROFILE_IMAGES_NFO3;
	}
	public void setTNP_CX_PROFILE_IMAGES_NFO3(String tNP_CX_PROFILE_IMAGES_NFO3) {
		TNP_CX_PROFILE_IMAGES_NFO3 = tNP_CX_PROFILE_IMAGES_NFO3;
	}
	public String getTNP_CX_PROFILE_IMAGES_NFO4() {
		return TNP_CX_PROFILE_IMAGES_NFO4;
	}
	public void setTNP_CX_PROFILE_IMAGES_NFO4(String tNP_CX_PROFILE_IMAGES_NFO4) {
		TNP_CX_PROFILE_IMAGES_NFO4 = tNP_CX_PROFILE_IMAGES_NFO4;
	}
	public String getTNP_CX_PROFILE_IMAGES_NFO5() {
		return TNP_CX_PROFILE_IMAGES_NFO5;
	}
	public void setTNP_CX_PROFILE_IMAGES_NFO5(String tNP_CX_PROFILE_IMAGES_NFO5) {
		TNP_CX_PROFILE_IMAGES_NFO5 = tNP_CX_PROFILE_IMAGES_NFO5;
	}
	
	
	
}
