package com.evidu.bank.model;

public class OrganizationVO {
	private String ORGANIZATION_NAME;
	private String ORGANIZATION_CPERSON;
	private String ORGANIZATION_ADDRESS;
	private String ORGANIZATION_EMAIL;
	private String ORGANIZATION_DATEJOINED;
	private String ORGANIZATION_LOGO;
	private String ORGANIZATION_CONTACTNO;
	
	public String getORGANIZATION_CONTACTNO() {
		return ORGANIZATION_CONTACTNO;
	}
	public void setORGANIZATION_CONTACTNO(String oRGANIZATION_CONTACTNO) {
		ORGANIZATION_CONTACTNO = oRGANIZATION_CONTACTNO;
	}
	private int ORGANIZATION_ID;
	
	public String getORGANIZATION_NAME() {
		return ORGANIZATION_NAME;
	}
	public void setORGANIZATION_NAME(String oRGANIZATION_NAME) {
		ORGANIZATION_NAME = oRGANIZATION_NAME;
	}
	public String getORGANIZATION_CPERSON() {
		return ORGANIZATION_CPERSON;
	}
	public void setORGANIZATION_CPERSON(String oRGANIZATION_CPERSON) {
		ORGANIZATION_CPERSON = oRGANIZATION_CPERSON;
	}
	public String getORGANIZATION_ADDRESS() {
		return ORGANIZATION_ADDRESS;
	}
	public void setORGANIZATION_ADDRESS(String oRGANIZATION_ADDRESS) {
		ORGANIZATION_ADDRESS = oRGANIZATION_ADDRESS;
	}
	public String getORGANIZATION_EMAIL() {
		return ORGANIZATION_EMAIL;
	}
	public void setORGANIZATION_EMAIL(String oRGANIZATION_EMAIL) {
		ORGANIZATION_EMAIL = oRGANIZATION_EMAIL;
	}
	public String getORGANIZATION_DATEJOINED() {
		return ORGANIZATION_DATEJOINED;
	}
	public void setORGANIZATION_DATEJOINED(String oRGANIZATION_DATEJOINED) {
		ORGANIZATION_DATEJOINED = oRGANIZATION_DATEJOINED;
	}
	public String getORGANIZATION_LOGO() {
		return ORGANIZATION_LOGO;
	}
	public void setORGANIZATION_LOGO(String oRGANIZATION_LOGO) {
		ORGANIZATION_LOGO = oRGANIZATION_LOGO;
	}
	public void setORGANIZATION_ID(int oRGANIZATION_ID ) {
		ORGANIZATION_ID=oRGANIZATION_ID;
		
	}
	public int getORGANIZATION_ID() {
		return ORGANIZATION_ID;
	}
}
